import 'dotenv/config';
import { Client, GatewayIntentBits, REST, Routes, SlashCommandBuilder, PermissionFlagsBits, EmbedBuilder, ActionRowBuilder, StringSelectMenuBuilder, ButtonBuilder, ButtonStyle, ModalBuilder, TextInputBuilder, TextInputStyle, ChannelType, PermissionsBitField } from 'discord.js';
import Database from 'better-sqlite3';
import pino from 'pino';
import { randomUUID } from 'node:crypto';
import net from 'node:net';
import { BOT_CONFIG } from './config.js';
import { SAFE_RUST_COMMANDS, CONTROLLED_RUST_COMMANDS, RUST_COMMAND_CATALOG } from './rust-command-catalog.js';

const log = pino({ level: process.env.LOG_LEVEL || 'info' });
const required = ['DISCORD_TOKEN', 'DISCORD_CLIENT_ID'];
for (const key of required) if (!process.env[key]?.trim()) throw new Error(`Missing ${key}. Add it in Railway Variables, then redeploy.`);
const token = process.env.DISCORD_TOKEN.trim();
const clientId = process.env.DISCORD_CLIENT_ID.trim();
const guildId = process.env.DISCORD_GUILD_ID?.trim();
if (!/^\d{17,20}$/.test(clientId)) throw new Error('DISCORD_CLIENT_ID must be the numeric Discord Application ID.');
if (guildId && !/^\d{17,20}$/.test(guildId)) throw new Error('DISCORD_GUILD_ID must be the numeric Discord Server ID.');
log.info({clientId, guildId: guildId || null, node: process.version}, 'Railway configuration loaded (token hidden)');

const db = new Database(process.env.DB_PATH || './rce-bot.sqlite');
db.pragma('journal_mode = WAL');
db.exec(`
CREATE TABLE IF NOT EXISTS clans (id TEXT PRIMARY KEY, guild_id TEXT NOT NULL, name TEXT NOT NULL, tag TEXT NOT NULL, owner_id TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS clan_members (clan_id TEXT NOT NULL, user_id TEXT NOT NULL, role TEXT NOT NULL DEFAULT 'member', PRIMARY KEY(clan_id,user_id));
CREATE TABLE IF NOT EXISTS servers (id TEXT PRIMARY KEY, guild_id TEXT NOT NULL, name TEXT NOT NULL, host TEXT NOT NULL, port INTEGER NOT NULL, rcon_secret TEXT NOT NULL, enabled INTEGER NOT NULL DEFAULT 1, region TEXT NOT NULL DEFAULT 'EU', description TEXT NOT NULL DEFAULT '', notes TEXT NOT NULL DEFAULT '', status TEXT NOT NULL DEFAULT 'pending', last_checked TEXT);

CREATE TABLE IF NOT EXISTS homes (guild_id TEXT NOT NULL, user_id TEXT NOT NULL, name TEXT NOT NULL, x REAL, y REAL, z REAL, PRIMARY KEY(guild_id,user_id,name));
CREATE TABLE IF NOT EXISTS stats (guild_id TEXT NOT NULL, user_id TEXT NOT NULL, username TEXT NOT NULL, kills INTEGER NOT NULL DEFAULT 0, playtime INTEGER NOT NULL DEFAULT 0, PRIMARY KEY(guild_id,user_id));
CREATE TABLE IF NOT EXISTS events (id TEXT PRIMARY KEY, guild_id TEXT NOT NULL, name TEXT NOT NULL, type TEXT NOT NULL, status TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS settings (guild_id TEXT PRIMARY KEY, log_channel_id TEXT, killfeed_channel_id TEXT, prefix TEXT NOT NULL DEFAULT '/');
CREATE TABLE IF NOT EXISTS scheduled_tasks (id TEXT PRIMARY KEY, guild_id TEXT NOT NULL, kind TEXT NOT NULL, payload TEXT NOT NULL, run_at TEXT NOT NULL, enabled INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS vip_members (guild_id TEXT NOT NULL, user_id TEXT NOT NULL, tier TEXT NOT NULL, expires_at TEXT, PRIMARY KEY(guild_id,user_id));
CREATE TABLE IF NOT EXISTS zones (id TEXT PRIMARY KEY, guild_id TEXT NOT NULL, name TEXT NOT NULL, type TEXT NOT NULL, x REAL NOT NULL, y REAL NOT NULL, z REAL NOT NULL, radius REAL NOT NULL);
CREATE TABLE IF NOT EXISTS audit_logs (id TEXT PRIMARY KEY, guild_id TEXT NOT NULL, actor_id TEXT NOT NULL, action TEXT NOT NULL, target TEXT, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS automod (guild_id TEXT PRIMARY KEY, enabled INTEGER NOT NULL DEFAULT 0, blocked_words TEXT NOT NULL DEFAULT '');
CREATE TABLE IF NOT EXISTS tickets (id TEXT PRIMARY KEY, guild_id TEXT NOT NULL, channel_id TEXT NOT NULL, user_id TEXT NOT NULL, region TEXT NOT NULL, category TEXT NOT NULL, question TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'open', created_at TEXT NOT NULL, closed_at TEXT);
CREATE TABLE IF NOT EXISTS ticket_panels (guild_id TEXT NOT NULL, channel_id TEXT NOT NULL, message_id TEXT NOT NULL, PRIMARY KEY(guild_id,channel_id,message_id));
CREATE TABLE IF NOT EXISTS setup_progress (guild_id TEXT PRIMARY KEY, roles_done INTEGER NOT NULL DEFAULT 0, logs_done INTEGER NOT NULL DEFAULT 0, server_done INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS setup_roles (guild_id TEXT NOT NULL, role_type TEXT NOT NULL, role_id TEXT NOT NULL, PRIMARY KEY(guild_id,role_type));
CREATE TABLE IF NOT EXISTS kit_settings (guild_id TEXT PRIMARY KEY, channel_id TEXT, configured_by TEXT, configured_at TEXT);
CREATE TABLE IF NOT EXISTS kits (id TEXT PRIMARY KEY, guild_id TEXT NOT NULL, name TEXT NOT NULL, description TEXT NOT NULL DEFAULT '', cooldown_hours INTEGER NOT NULL DEFAULT 24, created_by TEXT NOT NULL, created_at TEXT NOT NULL, UNIQUE(guild_id,name));
CREATE TABLE IF NOT EXISTS kit_claims (guild_id TEXT NOT NULL, kit_id TEXT NOT NULL, user_id TEXT NOT NULL, claimed_at TEXT NOT NULL, PRIMARY KEY(guild_id,kit_id,user_id));
CREATE TABLE IF NOT EXISTS whitelist_entries (guild_id TEXT NOT NULL, player TEXT NOT NULL, added_by TEXT NOT NULL, created_at TEXT NOT NULL, PRIMARY KEY(guild_id,player));
CREATE TABLE IF NOT EXISTS anticheat_settings (guild_id TEXT PRIMARY KEY, enabled INTEGER NOT NULL DEFAULT 0, mode TEXT NOT NULL DEFAULT 'monitor', updated_by TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS economy_accounts (guild_id TEXT NOT NULL, user_id TEXT NOT NULL, balance INTEGER NOT NULL DEFAULT 0, updated_at TEXT NOT NULL, PRIMARY KEY(guild_id,user_id));
CREATE TABLE IF NOT EXISTS economy_shop (id TEXT PRIMARY KEY, guild_id TEXT NOT NULL, name TEXT NOT NULL, price INTEGER NOT NULL, description TEXT NOT NULL DEFAULT '', created_at TEXT NOT NULL, UNIQUE(guild_id,name));
CREATE TABLE IF NOT EXISTS pending_player_actions (id TEXT PRIMARY KEY, guild_id TEXT NOT NULL, action TEXT NOT NULL, player TEXT NOT NULL, reason TEXT NOT NULL DEFAULT '', status TEXT NOT NULL DEFAULT 'pending_adapter', actor_id TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS wipe_requests (id TEXT PRIMARY KEY, guild_id TEXT NOT NULL, requested_by TEXT NOT NULL, confirmation TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'pending_adapter', announcement TEXT NOT NULL DEFAULT '', created_at TEXT NOT NULL);
`);
// Keep migrations idempotent and execute each ALTER independently.
const serverColumns = new Set(db.prepare('PRAGMA table_info(servers)').all().map(column => column.name));
const serverMigrations = [
  ['region', "ALTER TABLE servers ADD COLUMN region TEXT NOT NULL DEFAULT 'EU'"],
  ['description', "ALTER TABLE servers ADD COLUMN description TEXT NOT NULL DEFAULT ''"],
  ['notes', "ALTER TABLE servers ADD COLUMN notes TEXT NOT NULL DEFAULT ''"],
  ['status', "ALTER TABLE servers ADD COLUMN status TEXT NOT NULL DEFAULT 'pending'"],
  ['last_checked', 'ALTER TABLE servers ADD COLUMN last_checked TEXT']
];
for (const [column, migration] of serverMigrations) if (!serverColumns.has(column)) db.prepare(migration).run();


const STAFF_ROLE_TYPES = ['owner','co_owner','head_admin','admin','moderator'];
const OPEN_BEFORE_SERVER = new Set(['help','setup','server','ticket-panel','tickets','kits','clan','event','leaderboard','home','kit','vip','schedule-message','config','player','zone','logs','announcement','automod','maintenance','wipe','monitor']);
const getSetupState = guildId => db.prepare('SELECT roles_done,logs_done,server_done FROM setup_progress WHERE guild_id=?').get(guildId) || {roles_done:0,logs_done:0,server_done:0};
const isStaff = interaction => { if (!interaction.member) return false; if (interaction.member.permissions?.has(PermissionFlagsBits.Administrator) || interaction.member.permissions?.has(PermissionFlagsBits.ManageGuild)) return true; const roleIds = new Set((interaction.member.roles?.cache ? [...interaction.member.roles.cache.keys()] : []).map(String)); const configured = db.prepare(`SELECT role_id FROM setup_roles WHERE guild_id=? AND role_type IN (${STAFF_ROLE_TYPES.map(()=>'?').join(',')})`).all(interaction.guildId,...STAFF_ROLE_TYPES); return configured.some(r=>roleIds.has(String(r.role_id))); };
const getOnlineServer = guildId => db.prepare("SELECT * FROM servers WHERE guild_id=? AND enabled=1 AND status='online' AND last_checked IS NOT NULL AND last_checked >= datetime('now','-2 minutes') ORDER BY last_checked DESC LIMIT 1").get(guildId);
const audit = (guildId, actorId, action, target = null) => db.prepare('INSERT INTO audit_logs (id,guild_id,actor_id,action,target,created_at) VALUES (?,?,?,?,?,?)').run(randomUUID(), guildId, actorId, action, target, new Date().toISOString());
const requireStaff = async interaction => { if (isStaff(interaction)) return true; await interaction.reply({content:'🔒 This is a staff-only control. A server owner or configured Valora staff role is required.',ephemeral:true}); return false; };
const requireReadyServer = async interaction => { const setup=getSetupState(interaction.guildId); if(!setup.roles_done || !setup.logs_done || !setup.server_done) { await interaction.reply({content:'🧩 Finish `/setup` first. Roles, Logging, and Server must all be complete before gameplay commands unlock.',ephemeral:true}); return false; } const server=getOnlineServer(interaction.guildId); if(!server) { await interaction.reply({content:'🟡 No Rust server is online. Run `/server test` after configuring the server; commands unlock only after a successful connectivity check.',ephemeral:true}); return false; } return true; };
const SETUP_STEPS = new Set(['roles','logs','server']);
const validText = (value, max=100) => typeof value === 'string' && value.trim().length > 0 && value.trim().length <= max;
const tcpStatus = server => new Promise(resolve => { const socket=net.createConnection({host:server.host,port:server.port}); let done=false; const finish=(status,detail='')=>{ if(done)return; done=true; socket.destroy(); resolve({status,detail}); }; socket.setTimeout(4000,()=>finish('offline','Connection timed out')); socket.once('connect',()=>finish('online','TCP connection accepted')); socket.once('error',error=>finish('offline', error.code === 'ECONNREFUSED' ? 'Connection refused' : 'TCP connection failed')); });
const pendingAdapter = subject => `${subject}\n\n**Status:** pending adapter. No live Rust action was performed because no authenticated provider adapter is configured.`;

const SAFE_CONSOLE_ACTIONS = new Set(['players','playerlistids','listid','banlistex','printpos','getbuildinginfo','global.players','global.playerlistids','global.listid','global.banlistex','chat.enabled','writecfg','env.time','weather.rain','adminclouds','adminfog','adminwind',...SAFE_RUST_COMMANDS]);
const CONTROLLED_CONSOLE_ACTIONS = new Set(CONTROLLED_RUST_COMMANDS);
const commands = [
  new SlashCommandBuilder().setName('help').setDescription('Show all RCE bot modules'),
  new SlashCommandBuilder().setName('server').setDescription('Manage and test Rust Console servers').addSubcommand(s=>s.setName('list').setDescription('List configured servers')).addSubcommand(s=>s.setName('add').setDescription('Add a server').addStringOption(o=>o.setName('name').setDescription('Display name').setRequired(true)).addStringOption(o=>o.setName('host').setDescription('RCON/API host').setRequired(true)).addIntegerOption(o=>o.setName('port').setDescription('RCON/API port').setRequired(true)).addStringOption(o=>o.setName('secret').setDescription('Private RCON secret').setRequired(true)).addStringOption(o=>o.setName('region').setDescription('Server region').setRequired(true).addChoices({name:'EU',value:'EU'},{name:'NA',value:'NA'})).addStringOption(o=>o.setName('description').setDescription('Server description')).addStringOption(o=>o.setName('notes').setDescription('Setup notes'))).addSubcommand(s=>s.setName('test').setDescription('Test TCP reachability for a configured server').addStringOption(o=>o.setName('name').setDescription('Server name').setRequired(true))),
  new SlashCommandBuilder().setName('console').setDescription('Run a command on a configured RCON server').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild).addStringOption(o=>o.setName('command').setDescription('Console command').setRequired(true)).addStringOption(o=>o.setName('server').setDescription('Server name').setRequired(true)),
  new SlashCommandBuilder().setName('clan').setDescription('Clan system').addSubcommand(s=>s.setName('create').setDescription('Create a clan').addStringOption(o=>o.setName('name').setDescription('Clan name').setRequired(true)).addStringOption(o=>o.setName('tag').setDescription('Short tag').setRequired(true))).addSubcommand(s=>s.setName('info').setDescription('View your clan')).addSubcommand(s=>s.setName('invite').setDescription('Invite a member').addUserOption(o=>o.setName('user').setDescription('Member').setRequired(true))).addSubcommand(s=>s.setName('leave').setDescription('Leave clan')).addSubcommand(s=>s.setName('promote').setDescription('Promote member').addUserOption(o=>o.setName('user').setDescription('Member').setRequired(true))),
  new SlashCommandBuilder().setName('event').setDescription('Events: Nuketown, KOTH, Maze, Snowroams and more').addSubcommand(s=>s.setName('start').setDescription('Start an event').addStringOption(o=>o.setName('type').setDescription('Event type').setRequired(true).addChoices(...['Nuketown','KOTH','Maze','Snowroams','Custom'].map(x=>({name:x,value:x.toLowerCase()}))))).addSubcommand(s=>s.setName('list').setDescription('List active events')).addSubcommand(s=>s.setName('end').setDescription('End an event').addStringOption(o=>o.setName('id').setDescription('Event ID').setRequired(true))),
  new SlashCommandBuilder().setName('leaderboard').setDescription('View leaderboards').addStringOption(o=>o.setName('type').setDescription('Leaderboard').setRequired(true).addChoices({name:'Kills',value:'kills'},{name:'Playtime',value:'playtime'},{name:'Events',value:'events'})),
  new SlashCommandBuilder().setName('home').setDescription('TP home system').addSubcommand(s=>s.setName('set').setDescription('Save a home').addStringOption(o=>o.setName('name').setDescription('Home name').setRequired(true)).addNumberOption(o=>o.setName('x').setDescription('X').setRequired(true)).addNumberOption(o=>o.setName('y').setDescription('Y').setRequired(true)).addNumberOption(o=>o.setName('z').setDescription('Z').setRequired(true))).addSubcommand(s=>s.setName('list').setDescription('List homes')).addSubcommand(s=>s.setName('remove').setDescription('Remove a home').addStringOption(o=>o.setName('name').setDescription('Home name').setRequired(true))),
  new SlashCommandBuilder().setName('kit').setDescription('Automatic kits').addSubcommand(s=>s.setName('give').setDescription('Give a kit').addStringOption(o=>o.setName('name').setDescription('Kit name').setRequired(true)).addUserOption(o=>o.setName('user').setDescription('Target'))).addSubcommand(s=>s.setName('create').setDescription('Create kit').addStringOption(o=>o.setName('name').setDescription('Kit name').setRequired(true)).addStringOption(o=>o.setName('description').setDescription('Description'))).addSubcommand(s=>s.setName('claim').setDescription('Claim kit').addStringOption(o=>o.setName('name').setDescription('Kit name').setRequired(true))).addSubcommand(s=>s.setName('grab-all').setDescription('Request all kits')),
  new SlashCommandBuilder().setName('kits').setDescription('Configure and manage Emote Kits').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild).addSubcommand(s=>s.setName('config').setDescription('Show the Emote Kits setup instructions')),
  new SlashCommandBuilder().setName('vip').setDescription('VIP management').addSubcommand(s=>s.setName('add').setDescription('Add VIP').addUserOption(o=>o.setName('user').setDescription('User').setRequired(true)).addStringOption(o=>o.setName('tier').setDescription('Tier').setRequired(true))).addSubcommand(s=>s.setName('list').setDescription('List VIP members')),
  new SlashCommandBuilder().setName('schedule-message').setDescription('Schedule a Discord message').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild).addStringOption(o=>o.setName('message').setDescription('Message text').setRequired(true)).addStringOption(o=>o.setName('run_at').setDescription('Future ISO time').setRequired(true)),
  new SlashCommandBuilder().setName('whitelist').setDescription('Manage local whitelist records').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild).addSubcommand(s=>s.setName('add').setDescription('Add player').addStringOption(o=>o.setName('player').setDescription('Player name or ID').setRequired(true))).addSubcommand(s=>s.setName('remove').setDescription('Remove player').addStringOption(o=>o.setName('player').setDescription('Player name or ID').setRequired(true))).addSubcommand(s=>s.setName('list').setDescription('List players')),
  new SlashCommandBuilder().setName('anticheat').setDescription('Configure safe anticheat monitoring').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild).addSubcommand(s=>s.setName('config').setDescription('Configure monitoring').addBooleanOption(o=>o.setName('enabled').setDescription('Enable monitoring').setRequired(true)).addStringOption(o=>o.setName('mode').setDescription('Mode').setRequired(true).addChoices({name:'Monitor',value:'monitor'},{name:'Review queue',value:'review'}))),
  new SlashCommandBuilder().setName('economy').setDescription('Community economy').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild).addSubcommand(s=>s.setName('balance').setDescription('View balance').addUserOption(o=>o.setName('user').setDescription('User'))).addSubcommand(s=>s.setName('add').setDescription('Add credits').addUserOption(o=>o.setName('user').setDescription('User').setRequired(true)).addIntegerOption(o=>o.setName('amount').setDescription('Credits').setRequired(true).setMinValue(1))).addSubcommand(s=>s.setName('shop').setDescription('List shop items')),
  new SlashCommandBuilder().setName('player-manage').setDescription('Record player moderation action').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild).addSubcommand(s=>s.setName('kick').setDescription('Queue kick').addStringOption(o=>o.setName('player').setDescription('Player').setRequired(true)).addStringOption(o=>o.setName('reason').setDescription('Reason'))).addSubcommand(s=>s.setName('ban').setDescription('Queue ban').addStringOption(o=>o.setName('player').setDescription('Player').setRequired(true)).addStringOption(o=>o.setName('reason').setDescription('Reason'))),
  new SlashCommandBuilder().setName('server-wipe').setDescription('Prepare guarded wipe request').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild).addStringOption(o=>o.setName('confirmation').setDescription('Type WIPE_CONFIRMATION exactly').setRequired(true)).addStringOption(o=>o.setName('announcement').setDescription('Optional announcement')),
  new SlashCommandBuilder().setName('wipe').setDescription('Wipe information').addSubcommand(s=>s.setName('info').setDescription('Show latest request')).addSubcommand(s=>s.setName('announcement').setDescription('Show latest announcement')),
  new SlashCommandBuilder().setName('monitor').setDescription('Safe server monitor').addSubcommand(s=>s.setName('status').setDescription('Show status')),
  new SlashCommandBuilder().setName('config').setDescription('Configure logs, kill feed and automation').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild).addStringOption(o=>o.setName('log_channel').setDescription('Log channel ID')).addStringOption(o=>o.setName('killfeed_channel').setDescription('Kill feed channel ID')),
  new SlashCommandBuilder().setName('schedule').setDescription('Schedule a message or server command').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild).addStringOption(o=>o.setName('kind').setDescription('message or command').setRequired(true).addChoices({name:'Message',value:'message'},{name:'Command',value:'command'})).addStringOption(o=>o.setName('payload').setDescription('Message or console command').setRequired(true)).addStringOption(o=>o.setName('run_at').setDescription('Future ISO time').setRequired(true)),
  new SlashCommandBuilder().setName('setup').setDescription('Open the step-by-step Server Setup Hub'),
  new SlashCommandBuilder().setName('player').setDescription('Player tools').addSubcommand(s=>s.setName('info').setDescription('View a player record').addUserOption(o=>o.setName('user').setDescription('Discord user'))).addSubcommand(s=>s.setName('stats').setDescription('View saved stats').addUserOption(o=>o.setName('user').setDescription('Discord user'))),
  new SlashCommandBuilder().setName('zone').setDescription('Custom zones').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild).addSubcommand(s=>s.setName('create').setDescription('Create a zone').addStringOption(o=>o.setName('name').setDescription('Zone name').setRequired(true)).addStringOption(o=>o.setName('type').setDescription('Zone type').setRequired(true)).addNumberOption(o=>o.setName('x').setDescription('X').setRequired(true)).addNumberOption(o=>o.setName('y').setDescription('Y').setRequired(true)).addNumberOption(o=>o.setName('z').setDescription('Z').setRequired(true)).addNumberOption(o=>o.setName('radius').setDescription('Radius').setRequired(true))).addSubcommand(s=>s.setName('list').setDescription('List zones')).addSubcommand(s=>s.setName('delete').setDescription('Delete a zone').addStringOption(o=>o.setName('id').setDescription('Zone ID').setRequired(true))),
  new SlashCommandBuilder().setName('logs').setDescription('View recent bot audit logs').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild),
  new SlashCommandBuilder().setName('announcement').setDescription('Create a community announcement').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild).addStringOption(o=>o.setName('message').setDescription('Announcement text').setRequired(true)),
  new SlashCommandBuilder().setName('automod').setDescription('Configure basic automod').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild).addBooleanOption(o=>o.setName('enabled').setDescription('Enable automod').setRequired(true)).addStringOption(o=>o.setName('blocked_words').setDescription('Comma-separated words')),
  new SlashCommandBuilder().setName('maintenance').setDescription('Show maintenance mode status').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild),
  new SlashCommandBuilder().setName('ticket-panel').setDescription('Post the Valora RCE Bot support ticket panel').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild),
  new SlashCommandBuilder().setName('tickets').setDescription('Show support ticket status').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild)
].map(c=>c.toJSON());

const client = new Client({ intents: [GatewayIntentBits.Guilds, GatewayIntentBits.GuildMembers, GatewayIntentBits.GuildMessages] });
const BRAND = 'Valora RCE Bot';
const BRAND_LOGO = process.env.BRAND_LOGO_URL || '';
const BRAND_BANNER = process.env.BRAND_BANNER_URL || '';
const brandEmbed = (embed) => { if (BRAND_LOGO) embed.setThumbnail(BRAND_LOGO); if (BRAND_BANNER) embed.setImage(BRAND_BANNER); return embed; };
const ticketPanel = (guildId) => {
  const total=db.prepare("SELECT COUNT(*) AS n FROM tickets WHERE guild_id=? AND status='open'").get(guildId)?.n || 0;
  const eu=db.prepare("SELECT COUNT(*) AS n FROM tickets WHERE guild_id=? AND status='open' AND region='EU'").get(guildId)?.n || 0;
  const na=db.prepare("SELECT COUNT(*) AS n FROM tickets WHERE guild_id=? AND status='open' AND region='NA'").get(guildId)?.n || 0;
  const menu = new StringSelectMenuBuilder().setCustomId('ticket_category').setPlaceholder('📩  Select a support category').addOptions(
    {label:'Ticket General',value:'general',description:'General requests and questions',emoji:'📄'},
    {label:'Ticket Base',value:'base',description:'Base or area questions and problems',emoji:'🏠'},
    {label:'Ticket Clan',value:'clan',description:'Clan requests and clan problems',emoji:'👥'},
    {label:'Ticket Shop',value:'shop',description:'Store or product information',emoji:'💎'},
    {label:'Ticket Raid',value:'raid',description:'Bounty raid or raid-related problems',emoji:'⚠️'},
    {label:'Ticket Bug',value:'bug',description:'In-game or bot bugs and glitches',emoji:'🐛'}
  );
  return {embeds:[brandEmbed(new EmbedBuilder().setColor(0x7c3aed).setTitle('📩 Valora - Support').setDescription('For any issue you encounter or questions you have plz select one of the following choices.\n\nIf you are looking for the commands list | how they work, do `/help`. This will provide you the full list of commands and make response time quicker!').addFields({name:'📄 Ticket General',value:'For any request or question that is not specified in the following categories.'},{name:'🏠 Ticket Base',value:'Any questions or problems related to your base or your area can be discussed in this ticket.'},{name:'👥 Ticket Clan',value:'Ticket made to respond to clan requests or possible specific problems.'},{name:'💎 Ticket Shop',value:'Information about our online store or any product.'},{name:'⚠️ Ticket Raid',value:'Ticket made for bounty raid or raid-related problems.'},{name:'🐛 Ticket Bug',value:'For any bug/glitch found in-game or with our bots.'},{name:'📊 Support Status',value:`**Open Tickets (Total):** ${total}\n**Open EU Tickets:** ${eu}\n**Open NA Tickets:** ${na}\n**Response Speed:** ⚡ Fast\n**Estimated Help Time:** ⏱️ 12 mins`}).setFooter({text:'Support - Valora 5x [EU] • 2026'}).setTimestamp())],components:[new ActionRowBuilder().addComponents(menu)]};
};
const refreshTicketPanels = async (guildId) => {
  const rows=db.prepare('SELECT channel_id,message_id FROM ticket_panels WHERE guild_id=?').all(guildId);
  for (const row of rows) { try { const channel=await client.channels.fetch(row.channel_id); const message=await channel.messages.fetch(row.message_id); await message.edit(ticketPanel(guildId)); } catch (error) { db.prepare('DELETE FROM ticket_panels WHERE guild_id=? AND channel_id=? AND message_id=?').run(guildId,row.channel_id,row.message_id); log.warn({err:error,guildId,channelId:row.channel_id,messageId:row.message_id}, 'Removed stale ticket panel row'); } }
};
const reply = (i, title, description, fields=[]) => i.reply({ embeds: [brandEmbed(new EmbedBuilder().setColor(0x7c3aed).setTitle(`⚡ ${title}`).setDescription(description).addFields(fields).setFooter({text:BRAND}).setTimestamp())] });
const commandNav = () => new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('nav_help').setLabel('Command guide').setEmoji('📚').setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId('nav_ticket').setLabel('Open support').setEmoji('🎫').setStyle(ButtonStyle.Secondary));
const setupPanel = (guildId) => {
  const row=db.prepare('SELECT roles_done,logs_done,server_done FROM setup_progress WHERE guild_id=?').get(guildId) || {roles_done:0,logs_done:0,server_done:0};
  const buttons=new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('setup_roles').setLabel('Roles').setEmoji('👥').setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId('setup_logs').setLabel('Logging').setEmoji('📋').setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId('setup_server').setLabel('Server').setEmoji('🖥️').setStyle(ButtonStyle.Primary));
  const mark=v=>v?'✅ Complete':'❌ Pending';
  return {embeds:[brandEmbed(new EmbedBuilder().setColor(0x2563eb).setTitle('🧩 Server Setup Hub').setDescription('Welcome to the step-by-step setup!\nYou must complete the steps in order to unlock the next section.\n\nClick a blue button below to start or edit a section.').addFields({name:'Current Progress',value:`• **Step 1: Roles:** ${mark(row.roles_done)}\n• **Step 2: Logging:** ${mark(row.logs_done)}\n• **Step 3: Server:** ${mark(row.server_done)}`}).setFooter({text:'Valora RCE Bot • Setup Hub'}).setTimestamp())],components:[buttons]};
};
const ROLE_STEPS={1:{key:'owner',name:'Owner',skip:false},2:{key:'co_owner',name:'Co-Owner',skip:true},3:{key:'head_admin',name:'Head Admin',skip:true},4:{key:'admin',name:'Admin',skip:true},5:{key:'moderator',name:'Moderator',skip:true},6:{key:'linked',name:'Linked',skip:false}};
const setupRolesPanel = (guildId, step=1) => {
  const current=ROLE_STEPS[step]||ROLE_STEPS[1];
  const used=new Set(db.prepare('SELECT role_id FROM setup_roles WHERE guild_id=?').all(guildId).map(r=>r.role_id));
  const roles=[...client.guilds.cache.get(guildId)?.roles.cache.values()||[]].filter(r=>r.id!==guildId&&!r.managed&&!used.has(r.id)).slice(0,25);
  const roleMenu=new StringSelectMenuBuilder().setCustomId(`setup_role_select:${step}`).setPlaceholder('Select a role…').addOptions(roles.length?roles.map(r=>({label:r.name.slice(0,100),value:r.id,description:`Use ${r.name} as ${current.name} Role`})):[{label:'No roles found',value:'none',description:'Use Auto-Create to make the role'}]);
  const auto=new ButtonBuilder().setCustomId(`setup_role_auto:${step}`).setLabel('Auto-Create').setEmoji('✨').setStyle(ButtonStyle.Primary);
  const find=new ButtonBuilder().setCustomId(`setup_role_find:${step}`).setLabel('Find a role').setEmoji('🔎').setStyle(ButtonStyle.Secondary);
  const components=[new ActionRowBuilder().addComponents(roleMenu),new ActionRowBuilder().addComponents(find,auto)];
  if(current.skip) components[1].addComponents(new ButtonBuilder().setCustomId(`setup_role_skip:${step}`).setLabel('Skip').setEmoji('⏭️').setStyle(ButtonStyle.Secondary));
  if(step>1) components[1].addComponents(new ButtonBuilder().setCustomId(`setup_role_back:${step}`).setLabel('Back').setEmoji('◀️').setStyle(ButtonStyle.Secondary));
  return {embeds:[brandEmbed(new EmbedBuilder().setColor(0x2563eb).setTitle(`🧩 Step 1: Roles (${step}/6)`).setDescription(`Please configure the **${current.name} Role**.\n\n• Choose an existing role from the dropdown.\n• Click **Auto-Create** to make one.${current.skip?'\n• Click **Skip** if not used.':''}${current.skip?'':'\n\n⚠️ **Mandatory.**'}`).setFooter({text:'Valora RCE Bot V0.1.2 • Setup'}).setTimestamp())],components};
};
const rolesSavedPanel = () => ({embeds:[brandEmbed(new EmbedBuilder().setColor(0x22c55e).setTitle('✅ Roles Saved').setDescription('Roles have been configured successfully. You may now proceed to Logging.').setFooter({text:'Valora RCE Bot V0.1.2 • Setup'}).setTimestamp())]});

client.once('ready', async () => {
  const rest = new REST({version:'10'}).setToken(token);
  const applicationId = client.user.id;
  const configuredGuildId = guildId;
  try {
    if (configuredGuildId) {
      await rest.put(Routes.applicationGuildCommands(applicationId, configuredGuildId), {body:commands});
      await rest.put(Routes.applicationCommands(applicationId), {body:[]});
      log.info({guildId:configuredGuildId,commandCount:commands.length}, 'Slash commands registered only to configured guild; global duplicates removed');
    } else {
      await rest.put(Routes.applicationCommands(applicationId), {body:commands});
      // Remove stale guild-scoped copies where the bot can see the guild; this prevents
      // old guild registrations from shadowing the canonical global command set.
      await Promise.all([...client.guilds.cache.keys()].map(id => rest.put(Routes.applicationGuildCommands(applicationId, id), {body:[]})));
      log.info({commandCount:commands.length,clearedGuilds:client.guilds.cache.size}, 'Slash commands registered globally and guild duplicates removed');
    }
    await client.user.setPresence({activities:[{name:'Rust Console communities',type:0}],status:'online'});
    log.info({user:client.user.tag,brand:BRAND,commandCount:commands.length}, 'Valora RCE Bot online');
  } catch (error) {
    log.error({err:error,applicationId,configuredGuildId,joinedGuilds:[...client.guilds.cache.keys()]}, 'Slash-command registration failed; check token, scopes, and guild ID');
  }
});

client.on('interactionCreate', async i => {
  try {
    if (i.guildId && (i.isButton() || i.isStringSelectMenu() || i.isModalSubmit()) && (i.customId.startsWith('setup_') || i.customId.startsWith('setup_role_'))) {
      if (!(await requireStaff(i))) return;
    }
    if (i.isStringSelectMenu() && i.customId === 'ticket_category') {
      const category=i.values[0];
      const regionMenu=new StringSelectMenuBuilder().setCustomId(`ticket_region:${category}`).setPlaceholder('Choose your region').addOptions({label:'EU',value:'EU',description:'European support team'},{label:'NA — COMING SOON',value:'NA',description:'North American tickets are coming soon'});
      return i.update({components:[new ActionRowBuilder().addComponents(regionMenu)]});
    }
    if (i.isStringSelectMenu() && i.customId.startsWith('ticket_region:')) {
      const category=i.customId.split(':')[1],region=i.values[0];
      if (region === 'NA') return i.reply({content:'NA support is coming soon. Please select EU for now.',ephemeral:true});
      const modal=new ModalBuilder().setCustomId(`ticket_modal:${category}:${region}`).setTitle(`${region} support ticket`);
      const linkName=new TextInputBuilder().setCustomId('link_name').setLabel('What is your link name?').setStyle(TextInputStyle.Short).setPlaceholder('Your in-game/server link name').setRequired(true).setMaxLength(100);
      const issue=new TextInputBuilder().setCustomId('issue').setLabel('What is wrong?').setStyle(TextInputStyle.Short).setPlaceholder('Briefly describe the problem').setRequired(true).setMaxLength(200);
      const details=new TextInputBuilder().setCustomId('details').setLabel('Tell us everything').setStyle(TextInputStyle.Paragraph).setPlaceholder('Include server, player name, time, screenshots, error messages, and what you tried.').setRequired(true).setMaxLength(1000);
      return i.showModal(modal.addComponents(new ActionRowBuilder().addComponents(linkName),new ActionRowBuilder().addComponents(issue),new ActionRowBuilder().addComponents(details)));
    }
    if (i.isModalSubmit() && i.customId.startsWith('ticket_modal:')) {
      if (!i.guildId || !i.guild) return i.reply({content:'Tickets can only be opened inside a server.',ephemeral:true});
      const [,category,region]=i.customId.split(':'), linkName=i.fields.getTextInputValue('link_name'), issue=i.fields.getTextInputValue('issue'), details=i.fields.getTextInputValue('details'), guild=i.guild;
      const question=`**Link name:** ${linkName}\n**What is wrong:** ${issue}\n\n**Details:**\n${details}`;
      const safeName=`${region.toLowerCase()}-${i.user.username}`.toLowerCase().replace(/[^a-z0-9-]/g,'').slice(0,70);
      const channel=await guild.channels.create({name:`ticket-${safeName}`,type:ChannelType.GuildText,topic:`${BRAND} | ${region} | ${category} | ${i.user.id}`,permissionOverwrites:[{id:guild.roles.everyone.id,deny:[PermissionsBitField.Flags.ViewChannel]},{id:i.user.id,allow:[PermissionsBitField.Flags.ViewChannel,PermissionsBitField.Flags.SendMessages,PermissionsBitField.Flags.ReadMessageHistory]},{id:guild.members.me.id,allow:[PermissionsBitField.Flags.ViewChannel,PermissionsBitField.Flags.SendMessages,PermissionsBitField.Flags.ManageChannels]}]});
      const id=randomUUID(); db.prepare('INSERT INTO tickets VALUES (?,?,?,?,?,?,?,?,?,?)').run(id,guild.id,channel.id,i.user.id,region,category,question,'open',new Date().toISOString(),null);
      const close=new ButtonBuilder().setCustomId(`ticket_close:${id}`).setLabel('Close ticket').setStyle(ButtonStyle.Danger);
      await channel.send({content:`<@${i.user.id}>`,embeds:[new EmbedBuilder().setColor(0x8b5cf6).setTitle('🎫 Valora RCE Support Ticket').setDescription('Thanks for contacting Valora RCE Bot. A support team member will review your request and reply here.').addFields({name:'🌍 Region',value:region,inline:true},{name:'🧩 Category',value:category,inline:true},{name:'🔗 Link name',value:linkName,inline:true},{name:'⚠️ What is wrong?',value:issue},{name:'📝 Full request',value:details.slice(0,1000)}).setFooter({text:BRAND})],components:[new ActionRowBuilder().addComponents(close)]});
      await refreshTicketPanels(guild.id); return i.reply({content:`✅ Your ${region} support ticket is open: ${channel}`,ephemeral:true});
    }
    if (i.isButton() && i.customId === 'nav_help') return i.reply({content:'Use `/help` any time to reopen the Valora RCE Bot command guide.',ephemeral:true});
    if (i.isStringSelectMenu() && i.customId.startsWith('setup_role_select:')) { const step=Number(i.customId.split(':')[1]), roleId=i.values[0], current=ROLE_STEPS[step]; if(roleId==='none') return i.reply({content:'No unused role is available. Use Auto-Create to make a new one.',ephemeral:true}); const already=db.prepare('SELECT role_type FROM setup_roles WHERE guild_id=? AND role_id=?').get(i.guildId,roleId); if(already) return i.reply({content:'That role is already assigned to another setup slot. Choose a different role.',ephemeral:true}); db.prepare('INSERT OR REPLACE INTO setup_roles VALUES (?,?,?)').run(i.guildId,current.key,roleId); db.prepare('INSERT OR IGNORE INTO setup_progress (guild_id) VALUES (?)').run(i.guildId); if(step<6) return i.update(setupRolesPanel(i.guildId,step+1)); db.prepare('UPDATE setup_progress SET roles_done=1 WHERE guild_id=?').run(i.guildId); return i.update(rolesSavedPanel()); }
    if (i.isButton() && i.customId === 'setup_roles') return i.update(setupRolesPanel(i.guildId,1));
    if (i.isButton() && i.customId.startsWith('setup_role_find:')) { const step=Number(i.customId.split(':')[1]); const modal=new ModalBuilder().setCustomId(`setup_role_search:${step}`).setTitle('Find an existing role'); const input=new TextInputBuilder().setCustomId('query').setLabel('Type a role name').setStyle(TextInputStyle.Short).setPlaceholder('Owner, Admin, Moderator…').setRequired(true).setMaxLength(100); return i.showModal(modal.addComponents(new ActionRowBuilder().addComponents(input))); }
    if (i.isButton() && i.customId.startsWith('setup_role_auto:')) { const step=Number(i.customId.split(':')[1]), current=ROLE_STEPS[step]; try { const role=await i.guild.roles.create({name:`Valora ${current.name}`,color:0x2563eb,reason:'Valora RCE setup'}); db.prepare('INSERT OR REPLACE INTO setup_roles VALUES (?,?,?)').run(i.guildId,current.key,role.id); db.prepare('INSERT OR IGNORE INTO setup_progress (guild_id) VALUES (?)').run(i.guildId); if(step<6) return i.update(setupRolesPanel(i.guildId,step+1)); db.prepare('UPDATE setup_progress SET roles_done=1 WHERE guild_id=?').run(i.guildId); return i.update(rolesSavedPanel()); } catch(error) { log.error({err:error,guildId:i.guildId}, 'Could not create setup role'); return i.reply({content:'I could not create that role. Give Valora RCE Bot the Manage Roles permission and move its bot role above the new role, then try again.',ephemeral:true}); } }
    if (i.isButton() && i.customId.startsWith('setup_role_back:')) { const step=Number(i.customId.split(':')[1]); return i.update(step<=1?setupPanel(i.guildId):setupRolesPanel(i.guildId,step-1)); }
    if (i.isButton() && i.customId.startsWith('setup_role_skip:')) { const step=Number(i.customId.split(':')[1]); if(step===6) return i.reply({content:'Linked Role is mandatory and cannot be skipped.',ephemeral:true}); if(step<6) return i.update(setupRolesPanel(i.guildId,step+1)); }
    if (i.isButton() && i.customId.startsWith('setup_')) { const step=i.customId.slice(6); const row=db.prepare('SELECT roles_done,logs_done,server_done FROM setup_progress WHERE guild_id=?').get(i.guildId)||{roles_done:0,logs_done:0,server_done:0}; if(step==='logs'&&!row.roles_done) return i.reply({content:'Complete Step 1: Roles before configuring Logging.',ephemeral:true}); if(step==='server'&&(!row.roles_done||!row.logs_done)) return i.reply({content:'Complete Roles and Logging before configuring the Server.',ephemeral:true}); const modal=new ModalBuilder().setCustomId(`setup_modal:${step}`).setTitle(`Setup • ${step[0].toUpperCase()+step.slice(1)}`); const input=new TextInputBuilder().setCustomId('value').setLabel(step==='roles'?'Role name to create':step==='logs'?'Log channel ID':'Server name').setStyle(TextInputStyle.Short).setPlaceholder(step==='roles'?'Support Team':step==='logs'?'123456789012345678':'My Rust Server').setRequired(true).setMaxLength(100); return i.showModal(modal.addComponents(new ActionRowBuilder().addComponents(input))); }
    if (i.isModalSubmit() && i.customId.startsWith('setup_role_search:')) { const step=Number(i.customId.split(':')[1]), query=i.fields.getTextInputValue('query').toLowerCase().trim(), used=new Set(db.prepare('SELECT role_id FROM setup_roles WHERE guild_id=?').all(i.guildId).map(r=>r.role_id)), matches=[...i.guild.roles.cache.values()].filter(r=>r.id!==i.guildId&&!r.managed&&!used.has(r.id)&&r.name.toLowerCase().includes(query)).slice(0,25); if(!matches.length) return i.reply({content:`No unused role matched “${query}”. Try another name or use Auto-Create.`,ephemeral:true}); const menu=new StringSelectMenuBuilder().setCustomId(`setup_role_select:${step}`).setPlaceholder('Choose the matching role').addOptions(matches.map(r=>({label:r.name.slice(0,100),value:r.id,description:`Use as ${ROLE_STEPS[step].name} Role`}))); return i.reply({content:`🔎 Matches for **${query}**`,components:[new ActionRowBuilder().addComponents(menu)],ephemeral:true}); }
    if (i.isModalSubmit() && i.customId.startsWith('setup_modal:')) { const step=i.customId.split(':')[1], value=i.fields.getTextInputValue('value'); if(!SETUP_STEPS.has(step)) return i.reply({content:'Unknown setup step.',ephemeral:true}); if(step==='logs' && !/^\d{17,20}$/.test(value)) return i.reply({content:'Enter a valid Discord channel ID.',ephemeral:true}); if(step==='server' && !db.prepare('SELECT 1 FROM servers WHERE guild_id=? AND name=?').get(i.guildId,value)) return i.reply({content:'Add the server with `/server add` before marking this step complete.',ephemeral:true}); if(step==='roles'){const role=await i.guild.roles.create({name:value,color:0x2563eb,reason:'Valora RCE setup'}); db.prepare('INSERT OR REPLACE INTO setup_roles VALUES (?,?,?)').run(i.guildId,'owner',role.id);} if(step==='logs') db.prepare('INSERT INTO settings(guild_id,log_channel_id) VALUES (?,?) ON CONFLICT(guild_id) DO UPDATE SET log_channel_id=excluded.log_channel_id').run(i.guildId,value); db.prepare('INSERT OR IGNORE INTO setup_progress (guild_id) VALUES (?)').run(i.guildId); const setupColumn={roles:'roles_done',logs:'logs_done',server:'server_done'}[step]; db.prepare(`UPDATE setup_progress SET ${setupColumn}=1 WHERE guild_id=?`).run(i.guildId); return i.reply({content:`✅ Step complete: ${step}. ${step==='roles'?'The role was created.':`Saved: ${value}`}`,ephemeral:true}); }
    if (i.isButton() && i.customId === 'nav_ticket') return i.reply({content:'Use `/ticket-panel` in your support channel to publish the support panel.',ephemeral:true});
    if (i.isButton() && i.customId.startsWith('ticket_close:')) { const id=i.customId.split(':')[1]; if (!i.guildId || !i.channelId || !(await requireStaff(i))) return; const ticket=db.prepare('SELECT * FROM tickets WHERE id=? AND guild_id=? AND channel_id=?').get(id,i.guildId,i.channelId); if (!ticket) return i.reply({content:'This ticket is invalid or belongs to another server/channel.',ephemeral:true}); if (ticket.status !== 'open') return i.reply({content:'This ticket is already closed.',ephemeral:true}); db.prepare("UPDATE tickets SET status='closed',closed_at=? WHERE id=? AND guild_id=? AND channel_id=? AND status='open'").run(new Date().toISOString(),id,i.guildId,i.channelId); audit(i.guildId,i.user.id,'ticket.closed',id); await refreshTicketPanels(i.guildId); await i.reply({content:'✅ Ticket closed. This channel will be removed in 5 seconds.',ephemeral:true}); setTimeout(()=>i.channel?.delete().catch(()=>{}),5000); return; }
    if (!i.isChatInputCommand()) return;
    if (['setup','server','ticket-panel','kits','config','logs','announcement','automod','maintenance','schedule-message','schedule','zone','tickets'].includes(i.commandName) && !(await requireStaff(i))) return; if (!OPEN_BEFORE_SERVER.has(i.commandName) && !(await requireReadyServer(i))) return;
    if (i.commandName === 'help') return i.reply({embeds:[new EmbedBuilder().setColor(0x7c3aed).setTitle('⚡ Valora RCE Bot').setDescription('Your all-in-one Rust Console community control centre. Every feature is separated per Discord server and protected by permissions.').addFields({name:'🛠️ Server Control',value:'`/server` — add and view servers\n`/console` — authorized management actions\n`/maintenance` — service status'},{name:'🎫 Community Support',value:'`/ticket-panel` — publish the support panel\n`/tickets` — live EU/NA ticket status\n`/announcement` — post community updates'},{name:'👥 Community Systems',value:'`/clan` — create and manage clans\n`/player` — player records and stats\n`/leaderboard` — kills, playtime, and events\n`/vip` — community VIP records'},{name:'🎮 Gameplay Tools',value:'`/event` — Nuketown, KOTH, Maze, Snowroams\n`/home` — save and manage homes\n`/kit` — kit requests\n`/zone` — custom zone records'},{name:'🔧 Admin & Automation',value:'`/setup` · `/config` · `/logs` · `/automod` · `/schedule`'}).setFooter({text:`${BRAND} • Choose a command from the Discord menu`}).setTimestamp()],components:[commandNav()]});
    if (i.commandName === 'server') { const sub=i.options.getSubcommand(); if(sub==='list'){ const rows=db.prepare('SELECT name,host,port,region,status,last_checked,description FROM servers WHERE guild_id=? ORDER BY name').all(i.guildId); return reply(i,'Configured servers',rows.length?rows.map(r=>`• **${r.name}** [${r.region}] — ${r.status} (${r.host}:${r.port})`).join('\n'):'No servers configured. Use `/server add`.'); } if(sub==='add'){ const name=i.options.getString('name').trim(),host=i.options.getString('host').trim(),port=i.options.getInteger('port'),secret=i.options.getString('secret'),region=i.options.getString('region'),description=i.options.getString('description')||'',notes=i.options.getString('notes')||''; if(!validText(name,80)||!validText(host,253)||!validText(secret,500)||port<1||port>65535) return reply(i,'Invalid server details','Name, host, secret, and port must be valid.'); if(!/^[a-zA-Z0-9.-]+$/.test(host)) return reply(i,'Invalid host','Use a hostname or IP address only.'); try { db.prepare('INSERT INTO servers (id,guild_id,name,host,port,rcon_secret,region,description,notes,status) VALUES (?,?,?,?,?,?,?,?,?,?)').run(randomUUID(),i.guildId,name,host,port,secret,region,description.slice(0,500),notes.slice(0,500),'pending'); audit(i.guildId,i.user.id,'server.added',name); return reply(i,'Server saved','Configuration saved. Run `/server test` to perform a TCP reachability check; the secret is never displayed.'); } catch(e) { if(e.code==='SQLITE_CONSTRAINT_UNIQUE') return reply(i,'Server already exists','Choose a different server name.'); throw e; } } const name=i.options.getString('name'); const server=db.prepare('SELECT * FROM servers WHERE guild_id=? AND name=? AND enabled=1').get(i.guildId,name); if(!server) return reply(i,'Server not found','Use `/server list` to see configured server names.'); const result=await tcpStatus(server); db.prepare('UPDATE servers SET status=?,last_checked=? WHERE id=? AND guild_id=?').run(result.status,new Date().toISOString(),server.id,i.guildId); return reply(i,result.status==='online'?'Server reachable':'Server unreachable',`**${server.name}** TCP status: **${result.status}**\n${result.detail}\n\nThis checks TCP only; it does not authenticate RCON or execute commands.`); }
    if (i.commandName === 'clan') { const sub=i.options.getSubcommand(); if(sub==='create'){const name=i.options.getString('name').trim(),tag=i.options.getString('tag').trim().toUpperCase(); if(!validText(name,20)||!/^[A-Z0-9]{2,6}$/.test(tag)) return reply(i,'Invalid clan','Name must be 1–20 characters and tag must be 2–6 letters/numbers.'); if(db.prepare('SELECT 1 FROM clans c JOIN clan_members m ON m.clan_id=c.id WHERE c.guild_id=? AND m.user_id=?').get(i.guildId,i.user.id)) return reply(i,'Already in a clan','Leave your current clan first.'); const id=randomUUID(); db.prepare('INSERT INTO clans VALUES (?,?,?,?,?,?)').run(id,i.guildId,name,tag,i.user.id,new Date().toISOString()); db.prepare('INSERT INTO clan_members VALUES (?,?,?)').run(id,i.user.id,'owner'); audit(i.guildId,i.user.id,'clan.created',name); return reply(i,'Clan created',`**${name}** [${tag}] created locally.`); } if(sub==='info'){const c=db.prepare('SELECT c.*,COUNT(m.user_id) AS members FROM clans c JOIN clan_members m ON m.clan_id=c.id WHERE c.guild_id=? AND m.user_id=? GROUP BY c.id').get(i.guildId,i.user.id); return reply(i,'Clan info',c?`**${c.name}** [${c.tag}]\nOwner: <@${c.owner_id}>\nMembers: ${c.members}`:'You are not in a clan.'); } if(sub==='invite'){const c=db.prepare("SELECT c.* FROM clans c JOIN clan_members m ON m.clan_id=c.id WHERE c.guild_id=? AND m.user_id=? AND m.role IN ('owner','officer')").get(i.guildId,i.user.id); const u=i.options.getUser('user'); if(!c)return reply(i,'Clan owner/officer required','Only clan owners and officers can invite.'); if(db.prepare('SELECT 1 FROM clan_members WHERE clan_id=? AND user_id=?').get(c.id,u.id))return reply(i,'Already a member','That user is already in the clan.'); db.prepare('INSERT INTO clan_members VALUES (?,?,?)').run(c.id,u.id,'member'); return reply(i,'Member added',`<@${u.id}> was added to **${c.name}** locally.`); } }
    if (i.commandName === 'event') { const sub=i.options.getSubcommand(); if(sub==='start'){const type=i.options.getString('type'); const id=randomUUID(); db.prepare('INSERT INTO events VALUES (?,?,?,?,?,?)').run(id,i.guildId,type,type,'active',new Date().toISOString()); return reply(i,'Event started',`**${type}** is active locally (ID: \`${id.slice(0,8)}\`). Live game event execution is pending adapter.`);} if(sub==='list'){const rows=db.prepare("SELECT id,name,type,created_at FROM events WHERE guild_id=? AND status='active'").all(i.guildId); return reply(i,'Active events',rows.length?rows.map(r=>`• ${r.name} (${r.type}) — ${r.id.slice(0,8)}`).join('\n'):'No active events.');} const id=i.options.getString('id'); const changed=db.prepare("UPDATE events SET status='ended' WHERE guild_id=? AND id=? AND status='active'").run(i.guildId,id); return reply(i,changed.changes?'Event ended':'Event not found',changed.changes?'Local event record ended.':'No active event matched that ID.'); }
    if (i.commandName === 'leaderboard') { const type=i.options.getString('type'); if(type==='events') return reply(i,'Leaderboard','Event leaderboard is unavailable until event results are provided by an adapter.'); const rows=db.prepare(`SELECT username,${type} AS score FROM stats WHERE guild_id=? ORDER BY score DESC LIMIT 10`).all(i.guildId); return reply(i,`${type==='kills'?'Kills':'Playtime'} leaderboard`,rows.length?rows.map((r,n)=>`${n+1}. **${r.username}** — ${r.score}`).join('\n'):'No stats recorded.'); }

[Showing lines 1-226 of 240. Use offset=227 to continue.]