import 'dotenv/config';
import { Client, GatewayIntentBits, REST, Routes, SlashCommandBuilder, PermissionFlagsBits, EmbedBuilder, ActionRowBuilder, StringSelectMenuBuilder, ButtonBuilder, ButtonStyle, ModalBuilder, TextInputBuilder, TextInputStyle, ChannelType, PermissionsBitField } from 'discord.js';
import Database from 'better-sqlite3';
import pino from 'pino';
import { randomUUID } from 'node:crypto';

const log = pino({ level: process.env.LOG_LEVEL || 'info' });
const required = ['DISCORD_TOKEN', 'DISCORD_CLIENT_ID'];
for (const key of required) if (!process.env[key]?.trim()) throw new Error(`Missing ${key}. Add it in Railway Variables, then redeploy.`);
const token = process.env.DISCORD_TOKEN.trim();
const clientId = process.env.DISCORD_CLIENT_ID.trim();
const guildId = process.env.DISCORD_GUILD_ID?.trim();
if (!/^\d{17,20}$/.test(clientId)) throw new Error('DISCORD_CLIENT_ID must be the numeric Discord Application ID.');
if (guildId && !/^\d{17,20}$/.test(guildId)) throw new Error('DISCORD_GUILD_ID must be the numeric Discord Server ID.');
log.info({clientId, guildId: guildId || null, node: process.version}, 'Railway configuration loaded (token hidden)');

const db = new Database(process.env.DB_PATH || './rce-bot.sqlite');
db.pragma('journal_mode = WAL');
db.exec(`
CREATE TABLE IF NOT EXISTS clans (id TEXT PRIMARY KEY, guild_id TEXT NOT NULL, name TEXT NOT NULL, tag TEXT NOT NULL, owner_id TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS clan_members (clan_id TEXT NOT NULL, user_id TEXT NOT NULL, role TEXT NOT NULL DEFAULT 'member', PRIMARY KEY(clan_id,user_id));
CREATE TABLE IF NOT EXISTS servers (id TEXT PRIMARY KEY, guild_id TEXT NOT NULL, name TEXT NOT NULL, host TEXT NOT NULL, port INTEGER NOT NULL, rcon_secret TEXT NOT NULL, enabled INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS homes (guild_id TEXT NOT NULL, user_id TEXT NOT NULL, name TEXT NOT NULL, x REAL, y REAL, z REAL, PRIMARY KEY(guild_id,user_id,name));
CREATE TABLE IF NOT EXISTS stats (guild_id TEXT NOT NULL, user_id TEXT NOT NULL, username TEXT NOT NULL, kills INTEGER NOT NULL DEFAULT 0, playtime INTEGER NOT NULL DEFAULT 0, PRIMARY KEY(guild_id,user_id));
CREATE TABLE IF NOT EXISTS events (id TEXT PRIMARY KEY, guild_id TEXT NOT NULL, name TEXT NOT NULL, type TEXT NOT NULL, status TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS settings (guild_id TEXT PRIMARY KEY, log_channel_id TEXT, killfeed_channel_id TEXT, prefix TEXT NOT NULL DEFAULT '/');
CREATE TABLE IF NOT EXISTS scheduled_tasks (id TEXT PRIMARY KEY, guild_id TEXT NOT NULL, kind TEXT NOT NULL, payload TEXT NOT NULL, run_at TEXT NOT NULL, enabled INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS vip_members (guild_id TEXT NOT NULL, user_id TEXT NOT NULL, tier TEXT NOT NULL, expires_at TEXT, PRIMARY KEY(guild_id,user_id));
CREATE TABLE IF NOT EXISTS zones (id TEXT PRIMARY KEY, guild_id TEXT NOT NULL, name TEXT NOT NULL, type TEXT NOT NULL, x REAL NOT NULL, y REAL NOT NULL, z REAL NOT NULL, radius REAL NOT NULL);
CREATE TABLE IF NOT EXISTS audit_logs (id TEXT PRIMARY KEY, guild_id TEXT NOT NULL, actor_id TEXT NOT NULL, action TEXT NOT NULL, target TEXT, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS automod (guild_id TEXT PRIMARY KEY, enabled INTEGER NOT NULL DEFAULT 0, blocked_words TEXT NOT NULL DEFAULT '');
CREATE TABLE IF NOT EXISTS tickets (id TEXT PRIMARY KEY, guild_id TEXT NOT NULL, channel_id TEXT NOT NULL, user_id TEXT NOT NULL, region TEXT NOT NULL, category TEXT NOT NULL, question TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'open', created_at TEXT NOT NULL, closed_at TEXT);
CREATE TABLE IF NOT EXISTS ticket_panels (guild_id TEXT NOT NULL, channel_id TEXT NOT NULL, message_id TEXT NOT NULL, PRIMARY KEY(guild_id,channel_id,message_id));
CREATE TABLE IF NOT EXISTS setup_progress (guild_id TEXT PRIMARY KEY, roles_done INTEGER NOT NULL DEFAULT 0, logs_done INTEGER NOT NULL DEFAULT 0, server_done INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS setup_roles (guild_id TEXT NOT NULL, role_type TEXT NOT NULL, role_id TEXT NOT NULL, PRIMARY KEY(guild_id,role_type));
`);

const commands = [
  new SlashCommandBuilder().setName('help').setDescription('Show all RCE bot modules'),
  new SlashCommandBuilder().setName('server').setDescription('Manage Rust Console servers').addSubcommand(s=>s.setName('list').setDescription('List configured servers')).addSubcommand(s=>s.setName('add').setDescription('Add a server').addStringOption(o=>o.setName('name').setDescription('Display name').setRequired(true)).addStringOption(o=>o.setName('host').setDescription('RCON host').setRequired(true)).addIntegerOption(o=>o.setName('port').setDescription('RCON port').setRequired(true)).addStringOption(o=>o.setName('secret').setDescription('RCON secret').setRequired(true))),
  new SlashCommandBuilder().setName('console').setDescription('Run a command on a configured RCON server').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild).addStringOption(o=>o.setName('command').setDescription('Console command').setRequired(true)).addStringOption(o=>o.setName('server').setDescription('Server name').setRequired(true)),
  new SlashCommandBuilder().setName('clan').setDescription('Clan system').addSubcommand(s=>s.setName('create').setDescription('Create a clan').addStringOption(o=>o.setName('name').setDescription('Clan name').setRequired(true)).addStringOption(o=>o.setName('tag').setDescription('Short tag').setRequired(true))).addSubcommand(s=>s.setName('info').setDescription('View your clan')).addSubcommand(s=>s.setName('invite').setDescription('Invite a member').addUserOption(o=>o.setName('user').setDescription('Member').setRequired(true))),
  new SlashCommandBuilder().setName('event').setDescription('Events: Nuketown, KOTH, Maze, Snowroams and more').addSubcommand(s=>s.setName('start').setDescription('Start an event').addStringOption(o=>o.setName('type').setDescription('Event type').setRequired(true).addChoices(...['Nuketown','KOTH','Maze','Snowroams','Custom'].map(x=>({name:x,value:x.toLowerCase()}))))).addSubcommand(s=>s.setName('list').setDescription('List active events')).addSubcommand(s=>s.setName('end').setDescription('End an event').addStringOption(o=>o.setName('id').setDescription('Event ID').setRequired(true))),
  new SlashCommandBuilder().setName('leaderboard').setDescription('View leaderboards').addStringOption(o=>o.setName('type').setDescription('Leaderboard').setRequired(true).addChoices({name:'Kills',value:'kills'},{name:'Playtime',value:'playtime'},{name:'Events',value:'events'})),
  new SlashCommandBuilder().setName('home').setDescription('TP home system').addSubcommand(s=>s.setName('set').setDescription('Save a home').addStringOption(o=>o.setName('name').setDescription('Home name').setRequired(true)).addNumberOption(o=>o.setName('x').setDescription('X').setRequired(true)).addNumberOption(o=>o.setName('y').setDescription('Y').setRequired(true)).addNumberOption(o=>o.setName('z').setDescription('Z').setRequired(true))).addSubcommand(s=>s.setName('list').setDescription('List homes')).addSubcommand(s=>s.setName('remove').setDescription('Remove a home').addStringOption(o=>o.setName('name').setDescription('Home name').setRequired(true))),
  new SlashCommandBuilder().setName('kit').setDescription('Automatic kits').addSubcommand(s=>s.setName('give').setDescription('Give a kit').addStringOption(o=>o.setName('name').setDescription('Kit name').setRequired(true)).addUserOption(o=>o.setName('user').setDescription('Target'))),
  new SlashCommandBuilder().setName('vip').setDescription('VIP management').addSubcommand(s=>s.setName('add').setDescription('Add VIP').addUserOption(o=>o.setName('user').setDescription('User').setRequired(true)).addStringOption(o=>o.setName('tier').setDescription('Tier').setRequired(true))).addSubcommand(s=>s.setName('list').setDescription('List VIP members')),
  new SlashCommandBuilder().setName('config').setDescription('Configure logs, kill feed and automation').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild).addStringOption(o=>o.setName('log_channel').setDescription('Log channel ID')).addStringOption(o=>o.setName('killfeed_channel').setDescription('Kill feed channel ID')),
  new SlashCommandBuilder().setName('schedule').setDescription('Schedule a message or server command').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild).addStringOption(o=>o.setName('kind').setDescription('message or command').setRequired(true).addChoices({name:'Message',value:'message'},{name:'Command',value:'command'})).addStringOption(o=>o.setName('payload').setDescription('Message or console command').setRequired(true)).addStringOption(o=>o.setName('run_at').setDescription('Future ISO time').setRequired(true)),
  new SlashCommandBuilder().setName('setup').setDescription('Open the step-by-step Server Setup Hub'),
  new SlashCommandBuilder().setName('player').setDescription('Player tools').addSubcommand(s=>s.setName('info').setDescription('View a player record').addUserOption(o=>o.setName('user').setDescription('Discord user'))).addSubcommand(s=>s.setName('stats').setDescription('View saved stats').addUserOption(o=>o.setName('user').setDescription('Discord user'))),
  new SlashCommandBuilder().setName('zone').setDescription('Custom zones').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild).addSubcommand(s=>s.setName('create').setDescription('Create a zone').addStringOption(o=>o.setName('name').setDescription('Zone name').setRequired(true)).addStringOption(o=>o.setName('type').setDescription('Zone type').setRequired(true)).addNumberOption(o=>o.setName('x').setDescription('X').setRequired(true)).addNumberOption(o=>o.setName('y').setDescription('Y').setRequired(true)).addNumberOption(o=>o.setName('z').setDescription('Z').setRequired(true)).addNumberOption(o=>o.setName('radius').setDescription('Radius').setRequired(true))).addSubcommand(s=>s.setName('list').setDescription('List zones')).addSubcommand(s=>s.setName('delete').setDescription('Delete a zone').addStringOption(o=>o.setName('id').setDescription('Zone ID').setRequired(true))),
  new SlashCommandBuilder().setName('logs').setDescription('View recent bot audit logs').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild),
  new SlashCommandBuilder().setName('announcement').setDescription('Create a community announcement').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild).addStringOption(o=>o.setName('message').setDescription('Announcement text').setRequired(true)),
  new SlashCommandBuilder().setName('automod').setDescription('Configure basic automod').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild).addBooleanOption(o=>o.setName('enabled').setDescription('Enable automod').setRequired(true)).addStringOption(o=>o.setName('blocked_words').setDescription('Comma-separated words')),
  new SlashCommandBuilder().setName('maintenance').setDescription('Show maintenance mode status').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild),
  new SlashCommandBuilder().setName('ticket-panel').setDescription('Post the Valora RCE Bot support ticket panel').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild),
  new SlashCommandBuilder().setName('tickets').setDescription('Show support ticket status').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild)
].map(c=>c.toJSON());

const client = new Client({ intents: [GatewayIntentBits.Guilds, GatewayIntentBits.GuildMembers, GatewayIntentBits.GuildMessages] });
const BRAND = 'Valora RCE Bot';
const BRAND_LOGO = process.env.BRAND_LOGO_URL || '';
const BRAND_BANNER = process.env.BRAND_BANNER_URL || '';
const brandEmbed = (embed) => { if (BRAND_LOGO) embed.setThumbnail(BRAND_LOGO); if (BRAND_BANNER) embed.setImage(BRAND_BANNER); return embed; };
const ticketPanel = (guildId) => {
  const total=db.prepare("SELECT COUNT(*) AS n FROM tickets WHERE guild_id=? AND status='open'").get(guildId)?.n || 0;
  const eu=db.prepare("SELECT COUNT(*) AS n FROM tickets WHERE guild_id=? AND status='open' AND region='EU'").get(guildId)?.n || 0;
  const na=db.prepare("SELECT COUNT(*) AS n FROM tickets WHERE guild_id=? AND status='open' AND region='NA'").get(guildId)?.n || 0;
  const menu = new StringSelectMenuBuilder().setCustomId('ticket_category').setPlaceholder('🎫  Choose how we can help').addOptions(
    {label:'Rust Console Support',value:'rust_support',description:'Server, gameplay, RCON, and player help',emoji:'🛠️'},
    {label:'Bot Support',value:'bot_support',description:'Discord bot setup and command help',emoji:'🤖'},
    {label:'Report a Problem',value:'report',description:'Report a bug or community issue',emoji:'🚨'}
  );
  return {embeds:[brandEmbed(new EmbedBuilder().setColor(0x7c3aed).setTitle('🎫  Support Tickets').setDescription('Select a support option, then choose **EU** or **NA** before filling in your questions.\n\nOur team will see your private ticket and help you as soon as possible.').addFields({name:'📊  Support Status',value:`**Open Tickets (Total):** ${total}\n**Open EU Tickets:** ${eu}\n**Open NA Tickets:** ${na}\n**Response Speed:** ⚡ Fast\n**Estimated Help Time:** ⏱️ 12 mins`},{name:'🌍  Regions',value:'🇪🇺 EU support is available now\n🇺🇸 NA support is **COMING SOON**'}).setFooter({text:`${BRAND}  •  Status refreshes every minute`}).setTimestamp())],components:[new ActionRowBuilder().addComponents(menu)]};
};
const refreshTicketPanels = async (guildId) => {
  const rows=db.prepare('SELECT channel_id,message_id FROM ticket_panels WHERE guild_id=?').all(guildId);
  for (const row of rows) { try { const channel=await client.channels.fetch(row.channel_id); const message=await channel.messages.fetch(row.message_id); await message.edit(ticketPanel(guildId)); } catch (error) { log.warn({err:error,guildId}, 'Could not refresh ticket panel'); } }
};
const reply = (i, title, description, fields=[]) => i.reply({ embeds: [brandEmbed(new EmbedBuilder().setColor(0x7c3aed).setTitle(`⚡ ${title}`).setDescription(description).addFields(fields).setFooter({text:BRAND}).setTimestamp())] });
const commandNav = () => new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('nav_help').setLabel('Command guide').setEmoji('📚').setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId('nav_ticket').setLabel('Open support').setEmoji('🎫').setStyle(ButtonStyle.Secondary));
const setupPanel = (guildId) => {
  const row=db.prepare('SELECT roles_done,logs_done,server_done FROM setup_progress WHERE guild_id=?').get(guildId) || {roles_done:0,logs_done:0,server_done:0};
  const buttons=new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('setup_roles').setLabel('Roles').setEmoji('👥').setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId('setup_logs').setLabel('Logging').setEmoji('📋').setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId('setup_server').setLabel('Server').setEmoji('🖥️').setStyle(ButtonStyle.Primary));
  const mark=v=>v?'✅ Complete':'❌ Pending';
  return {embeds:[brandEmbed(new EmbedBuilder().setColor(0x2563eb).setTitle('🧩 Server Setup Hub').setDescription('Welcome to the step-by-step setup!\nYou must complete the steps in order to unlock the next section.\n\nClick a blue button below to start or edit a section.').addFields({name:'Current Progress',value:`• **Step 1: Roles:** ${mark(row.roles_done)}\n• **Step 2: Logging:** ${mark(row.logs_done)}\n• **Step 3: Server:** ${mark(row.server_done)}`}).setFooter({text:'Valora RCE Bot • Setup Hub'}).setTimestamp())],components:[buttons]};
};
const ROLE_STEPS={1:{key:'owner',name:'Owner',skip:false},2:{key:'co_owner',name:'Co-Owner',skip:true},3:{key:'head_admin',name:'Head Admin',skip:true},4:{key:'admin',name:'Admin',skip:true},5:{key:'moderator',name:'Moderator',skip:true},6:{key:'linked',name:'Linked',skip:false}};
const setupRolesPanel = (guildId, step=1) => {
  const current=ROLE_STEPS[step]||ROLE_STEPS[1];
  const used=new Set(db.prepare('SELECT role_id FROM setup_roles WHERE guild_id=?').all(guildId).map(r=>r.role_id));
  const roles=[...client.guilds.cache.get(guildId)?.roles.cache.values()||[]].filter(r=>r.id!==guildId&&!used.has(r.id)).slice(0,25);
  const roleMenu=new StringSelectMenuBuilder().setCustomId(`setup_role_select:${step}`).setPlaceholder('Select a role…').addOptions(roles.length?roles.map(r=>({label:r.name.slice(0,100),value:r.id,description:`Use ${r.name} as ${current.name} Role`})):[{label:'No roles found',value:'none',description:'Use Auto-Create to make the role'}]);
  const auto=new ButtonBuilder().setCustomId(`setup_role_auto:${step}`).setLabel('Auto-Create').setEmoji('✨').setStyle(ButtonStyle.Primary);
  const components=[new ActionRowBuilder().addComponents(roleMenu),new ActionRowBuilder().addComponents(auto)];
  if(current.skip) components[1].addComponents(new ButtonBuilder().setCustomId(`setup_role_skip:${step}`).setLabel('Skip').setEmoji('⏭️').setStyle(ButtonStyle.Secondary));
  if(step>1) components[1].addComponents(new ButtonBuilder().setCustomId(`setup_role_back:${step}`).setLabel('Back').setEmoji('◀️').setStyle(ButtonStyle.Secondary));
  return {embeds:[brandEmbed(new EmbedBuilder().setColor(0x2563eb).setTitle(`🧩 Step 1: Roles (${step}/6)`).setDescription(`Please configure the **${current.name} Role**.\n\n• Choose an existing role from the dropdown.\n• Click **Auto-Create** to make one.${current.skip?'\n• Click **Skip** if not used.':''}${current.skip?'':'\n\n⚠️ **Mandatory.**'}`).setFooter({text:'Valora RCE Bot V0.1.2 • Setup'}).setTimestamp())],components};
};
const rolesSavedPanel = () => ({embeds:[brandEmbed(new EmbedBuilder().setColor(0x22c55e).setTitle('✅ Roles Saved').setDescription('Roles have been configured successfully. You may now proceed to Logging.').setFooter({text:'Valora RCE Bot V0.1.2 • Setup'}).setTimestamp())]});

client.once('ready', async () => {
  const rest = new REST({version:'10'}).setToken(token);
  const applicationId = client.user.id;
  const configuredGuildId = guildId;
  try {
    if (configuredGuildId) {
      await rest.put(Routes.applicationGuildCommands(applicationId, configuredGuildId), {body:commands});
      log.info({guildId:configuredGuildId,commandCount:commands.length}, 'Slash commands registered to configured guild');
    } else {
      const guilds = [...client.guilds.cache.keys()];
      for (const guildId of guilds) {
        await rest.put(Routes.applicationGuildCommands(applicationId, guildId), {body:commands});
      }
      log.info({guildCount:guilds.length,commandCount:commands.length}, 'Slash commands registered to every joined guild');
    }
    await rest.put(Routes.applicationCommands(applicationId), {body:commands});
    await client.user.setPresence({activities:[{name:'Rust Console communities',type:0}],status:'online'});
    log.info({user:client.user.tag,brand:BRAND,commandCount:commands.length}, 'Valora RCE Bot online');
  } catch (error) {
    log.error({err:error,applicationId,configuredGuildId,joinedGuilds:[...client.guilds.cache.keys()]}, 'Slash-command registration failed; check token, scopes, and guild ID');
  }
});

client.on('interactionCreate', async i => {
  try {
    if (i.isStringSelectMenu() && i.customId === 'ticket_category') {
      const category=i.values[0];
      const regionMenu=new StringSelectMenuBuilder().setCustomId(`ticket_region:${category}`).setPlaceholder('Choose your region').addOptions({label:'EU',value:'EU',description:'European support team'},{label:'NA — COMING SOON',value:'NA',description:'North American tickets are coming soon'});
      return i.update({components:[new ActionRowBuilder().addComponents(regionMenu)]});
    }
    if (i.isStringSelectMenu() && i.customId.startsWith('ticket_region:')) {
      const category=i.customId.split(':')[1],region=i.values[0];
      if (region === 'NA') return i.reply({content:'NA support is coming soon. Please select EU for now.',ephemeral:true});
      const modal=new ModalBuilder().setCustomId(`ticket_modal:${category}:${region}`).setTitle(`${region} support ticket`);
      const linkName=new TextInputBuilder().setCustomId('link_name').setLabel('What is your link name?').setStyle(TextInputStyle.Short).setPlaceholder('Your in-game/server link name').setRequired(true).setMaxLength(100);
      const issue=new TextInputBuilder().setCustomId('issue').setLabel('What is wrong?').setStyle(TextInputStyle.Short).setPlaceholder('Briefly describe the problem').setRequired(true).setMaxLength(200);
      const details=new TextInputBuilder().setCustomId('details').setLabel('Tell us everything').setStyle(TextInputStyle.Paragraph).setPlaceholder('Include server, player name, time, screenshots, error messages, and what you tried.').setRequired(true).setMaxLength(1800);
      return i.showModal(modal.addComponents(new ActionRowBuilder().addComponents(linkName),new ActionRowBuilder().addComponents(issue),new ActionRowBuilder().addComponents(details)));
    }
    if (i.isModalSubmit() && i.customId.startsWith('ticket_modal:')) {
      const [,category,region]=i.customId.split(':'), linkName=i.fields.getTextInputValue('link_name'), issue=i.fields.getTextInputValue('issue'), details=i.fields.getTextInputValue('details'), guild=i.guild;
      const question=`**Link name:** ${linkName}\n**What is wrong:** ${issue}\n\n**Details:**\n${details}`;
      const safeName=`${region.toLowerCase()}-${i.user.username}`.toLowerCase().replace(/[^a-z0-9-]/g,'').slice(0,70);
      const channel=await guild.channels.create({name:`ticket-${safeName}`,type:ChannelType.GuildText,topic:`${BRAND} | ${region} | ${category} | ${i.user.id}`,permissionOverwrites:[{id:guild.roles.everyone.id,deny:[PermissionsBitField.Flags.ViewChannel]},{id:i.user.id,allow:[PermissionsBitField.Flags.ViewChannel,PermissionsBitField.Flags.SendMessages,PermissionsBitField.Flags.ReadMessageHistory]},{id:guild.members.me.id,allow:[PermissionsBitField.Flags.ViewChannel,PermissionsBitField.Flags.SendMessages,PermissionsBitField.Flags.ManageChannels]}]});
      const id=randomUUID(); db.prepare('INSERT INTO tickets VALUES (?,?,?,?,?,?,?,?,?,?)').run(id,guild.id,channel.id,i.user.id,region,category,question,'open',new Date().toISOString(),null);
      const close=new ButtonBuilder().setCustomId(`ticket_close:${id}`).setLabel('Close ticket').setStyle(ButtonStyle.Danger);
      await channel.send({content:`<@${i.user.id}>`,embeds:[new EmbedBuilder().setColor(0x8b5cf6).setTitle('🎫 Valora RCE Support Ticket').setDescription('Thanks for contacting Valora RCE Bot. A support team member will review your request and reply here.').addFields({name:'🌍 Region',value:region,inline:true},{name:'🧩 Category',value:category,inline:true},{name:'🔗 Link name',value:linkName,inline:true},{name:'⚠️ What is wrong?',value:issue},{name:'📝 Full request',value:details}).setFooter({text:BRAND})],components:[new ActionRowBuilder().addComponents(close)]});
      await refreshTicketPanels(guild.id); return i.reply({content:`✅ Your ${region} support ticket is open: ${channel}`,ephemeral:true});
    }
    if (i.isButton() && i.customId === 'nav_help') return i.reply({content:'Use `/help` any time to reopen the Valora RCE Bot command guide.',ephemeral:true});
    if (i.isStringSelectMenu() && i.customId.startsWith('setup_role_select:')) { const step=Number(i.customId.split(':')[1]), roleId=i.values[0], current=ROLE_STEPS[step]; if(roleId==='none') return i.reply({content:'No unused role is available. Use Auto-Create to make a new one.',ephemeral:true}); const already=db.prepare('SELECT role_type FROM setup_roles WHERE guild_id=? AND role_id=?').get(i.guildId,roleId); if(already) return i.reply({content:'That role is already assigned to another setup slot. Choose a different role.',ephemeral:true}); db.prepare('INSERT OR REPLACE INTO setup_roles VALUES (?,?,?)').run(i.guildId,current.key,roleId); db.prepare('INSERT OR IGNORE INTO setup_progress (guild_id) VALUES (?)').run(i.guildId); if(step<6) return i.update(setupRolesPanel(i.guildId,step+1)); db.prepare('UPDATE setup_progress SET roles_done=1 WHERE guild_id=?').run(i.guildId); return i.update(rolesSavedPanel()); }
    if (i.isButton() && i.customId === 'setup_roles') return i.update(setupRolesPanel(i.guildId,1));
    if (i.isButton() && i.customId.startsWith('setup_role_auto:')) { const step=Number(i.customId.split(':')[1]), current=ROLE_STEPS[step]; try { const role=await i.guild.roles.create({name:`Valora ${current.name}`,color:0x2563eb,reason:'Valora RCE setup'}); db.prepare('INSERT OR REPLACE INTO setup_roles VALUES (?,?,?)').run(i.guildId,current.key,role.id); db.prepare('INSERT OR IGNORE INTO setup_progress (guild_id) VALUES (?)').run(i.guildId); if(step<6) return i.update(setupRolesPanel(i.guildId,step+1)); db.prepare('UPDATE setup_progress SET roles_done=1 WHERE guild_id=?').run(i.guildId); return i.update(rolesSavedPanel()); } catch(error) { log.error({err:error,guildId:i.guildId}, 'Could not create setup role'); return i.reply({content:'I could not create that role. Give Valora RCE Bot the Manage Roles permission and move its bot role above the new role, then try again.',ephemeral:true}); } }
    if (i.isButton() && i.customId.startsWith('setup_role_back:')) { const step=Number(i.customId.split(':')[1]); return i.update(step<=1?setupPanel(i.guildId):setupRolesPanel(i.guildId,step-1)); }
    if (i.isButton() && i.customId.startsWith('setup_role_skip:')) { const step=Number(i.customId.split(':')[1]); if(step===6) return i.reply({content:'Linked Role is mandatory and cannot be skipped.',ephemeral:true}); if(step<6) return i.update(setupRolesPanel(i.guildId,step+1)); }
    if (i.isButton() && i.customId.startsWith('setup_')) { const step=i.customId.slice(6); const row=db.prepare('SELECT roles_done,logs_done,server_done FROM setup_progress WHERE guild_id=?').get(i.guildId)||{roles_done:0,logs_done:0,server_done:0}; if(step==='logs'&&!row.roles_done) return i.reply({content:'Complete Step 1: Roles before configuring Logging.',ephemeral:true}); if(step==='server'&&(!row.roles_done||!row.logs_done)) return i.reply({content:'Complete Roles and Logging before configuring the Server.',ephemeral:true}); const modal=new ModalBuilder().setCustomId(`setup_modal:${step}`).setTitle(`Setup • ${step[0].toUpperCase()+step.slice(1)}`); const input=new TextInputBuilder().setCustomId('value').setLabel(step==='roles'?'Role name to create':step==='logs'?'Log channel ID':'Server name').setStyle(TextInputStyle.Short).setPlaceholder(step==='roles'?'Support Team':step==='logs'?'123456789012345678':'My Rust Server').setRequired(true).setMaxLength(100); return i.showModal(modal.addComponents(new ActionRowBuilder().addComponents(input))); }
    if (i.isModalSubmit() && i.customId.startsWith('setup_modal:')) { const step=i.customId.split(':')[1], value=i.fields.getTextInputValue('value'); if(step==='roles'){await i.guild.roles.create({name:value,color:0x2563eb,reason:'Valora RCE setup'});} db.prepare('INSERT OR IGNORE INTO setup_progress (guild_id) VALUES (?)').run(i.guildId); db.prepare(`UPDATE setup_progress SET ${step}_done=1 WHERE guild_id=?`).run(i.guildId); return i.reply({content:`✅ Step complete: ${step}. ${step==='roles'?'The role was created.':`Saved: ${value}`}`,ephemeral:true}); }
    if (i.isButton() && i.customId === 'nav_ticket') return i.reply({content:'Use `/ticket-panel` in your support channel to publish the support panel.',ephemeral:true});
    if (i.isButton() && i.customId.startsWith('ticket_close:')) { const id=i.customId.split(':')[1]; db.prepare('UPDATE tickets SET status=\'closed\',closed_at=? WHERE id=?').run(new Date().toISOString(),id); await refreshTicketPanels(i.guildId); await i.reply({content:'✅ Ticket closed. This channel will be removed in 5 seconds.',ephemeral:true}); setTimeout(()=>i.channel?.delete().catch(()=>{}),5000); return; }
    if (!i.isChatInputCommand()) return;
    if (i.commandName === 'help') return i.reply({embeds:[new EmbedBuilder().setColor(0x7c3aed).setTitle('⚡ Valora RCE Bot').setDescription('Your all-in-one Rust Console community control centre. Every feature is separated per Discord server and protected by permissions.').addFields({name:'🛠️ Server Control',value:'`/server` — add and view servers\n`/console` — authorized management actions\n`/maintenance` — service status'},{name:'🎫 Community Support',value:'`/ticket-panel` — publish the support panel\n`/tickets` — live EU/NA ticket status\n`/announcement` — post community updates'},{name:'👥 Community Systems',value:'`/clan` — create and manage clans\n`/player` — player records and stats\n`/leaderboard` — kills, playtime, and events\n`/vip` — community VIP records'},{name:'🎮 Gameplay Tools',value:'`/event` — Nuketown, KOTH, Maze, Snowroams\n`/home` — save and manage homes\n`/kit` — kit requests\n`/zone` — custom zone records'},{name:'🔧 Admin & Automation',value:'`/setup` · `/config` · `/logs` · `/automod` · `/schedule`'}).setFooter({text:`${BRAND} • Choose a command from the Discord menu`}).setTimestamp()],components:[commandNav()]});
    if (i.commandName === 'server') { if(i.options.getSubcommand()==='add'){const n=i.options.getString('name'),h=i.options.getString('host'),p=i.options.getInteger('port'),s=i.options.getString('secret'); db.prepare('INSERT INTO servers VALUES (?,?,?,?,?,1)').run(randomUUID(),i.guildId,n,h,p,s); return reply(i,'Server connected',`**${n}** is now registered for this community.\n\nHost: \`${h}:${p}\`\nStatus: 🟡 Adapter pending\n\nThe secret is stored privately and never displayed.`,[{name:'Next step',value:'Use `/setup` to review the integration checklist.'}]);} const rows=db.prepare('SELECT name,host,port,enabled FROM servers WHERE guild_id=?').all(i.guildId); return reply(i,'Your Rust servers',rows.length?rows.map(r=>`• **${r.name}** — \`${r.host}:${r.port}\` — ${r.enabled?'🟢 Enabled':'🔴 Disabled'}`).join('\n'):'No servers are configured. Use `/server add` to begin.'); }
    if (i.commandName === 'clan') { const sub=i.options.getSubcommand(); if(sub==='create'){const name=i.options.getString('name'),tag=i.options.getString('tag'); const id=randomUUID(); db.prepare('INSERT INTO clans VALUES (?,?,?,?,?,?)').run(id,i.guildId,name,tag,i.user.id,new Date().toISOString()); db.prepare('INSERT INTO clan_members VALUES (?,?,?)').run(id,i.user.id,'owner'); return reply(i,'Clan created',`**[${tag}] ${name}** is ready.`);} const c=db.prepare('SELECT c.* FROM clans c JOIN clan_members m ON m.clan_id=c.id WHERE c.guild_id=? AND m.user_id=?').get(i.guildId,i.user.id); return reply(i,'Clan info',c?`**[${c.tag}] ${c.name}**\nOwner: <@${c.owner_id}>`:'You are not in a clan.'); }
    if (i.commandName === 'event') { const sub=i.options.getSubcommand(); if(sub==='start'){const type=i.options.getString('type'),id=randomUUID().slice(0,8); db.prepare('INSERT INTO events VALUES (?,?,?,?,?,?)').run(id,i.guildId,type,type,'active',new Date().toISOString()); return reply(i,'Event started',`**${type}** is live. Event ID: ${id}`);} const rows=db.prepare("SELECT id,name,type,status FROM events WHERE guild_id=? AND status='active'").all(i.guildId); return reply(i,'Active events',rows.length?rows.map(r=>`• ${r.id} **${r.name}** — ${r.type}`).join('\n'):'No active events.'); }
    if (i.commandName === 'leaderboard') { const type=i.options.getString('type'); if(type==='events') return reply(i,'Event leaderboard','🏆 Event placements will appear here as event results are recorded.\n\nRun events with `/event start` and keep results in one place for your community.'); const rows=db.prepare(`SELECT username,${type} AS score FROM stats WHERE guild_id=? ORDER BY score DESC LIMIT 10`).all(i.guildId); return reply(i,`Top ${type} players`,rows.length?rows.map((r,n)=>`${['🥇','🥈','🥉'][n]||`**${n+1}.**`} **${r.username}** — \`${r.score}\``).join('\n'):'No player stats recorded yet.\n\nPlayer data will appear once a supported Rust provider adapter is connected.'); }
    if (i.commandName === 'home') { const sub=i.options.getSubcommand(); if(sub==='set'){db.prepare('INSERT OR REPLACE INTO homes VALUES (?,?,?,?,?)').run(i.guildId,i.user.id,i.options.getString('name'),i.options.getNumber('x'),i.options.getNumber('y'),i.options.getNumber('z')); return reply(i,'Home saved','Coordinates saved for the RCON teleport adapter.');} const rows=db.prepare('SELECT name,x,y,z FROM homes WHERE guild_id=? AND user_id=?').all(i.guildId,i.user.id); return reply(i,'Your homes',rows.length?rows.map(r=>`• **${r.name}** — ${r.x}, ${r.y}, ${r.z}`).join('\n'):'No homes saved.'); }
    if (i.commandName === 'schedule') { const kind=i.options.getString('kind'),payload=i.options.getString('payload'),runAt=i.options.getString('run_at'); if(Number.isNaN(Date.parse(runAt)) || Date.parse(runAt)<=Date.now()) return reply(i,'Invalid schedule','Use a future ISO timestamp.'); db.prepare('INSERT INTO scheduled_tasks VALUES (?,?,?,?,?,1)').run(randomUUID(),i.guildId,kind,payload,new Date(runAt).toISOString()); return reply(i,'Scheduled',`${kind} task saved for ${new Date(runAt).toISOString()}.`); }
    if (i.commandName === 'vip') { const sub=i.options.getSubcommand(); if(sub==='add'){const user=i.options.getUser('user'),tier=i.options.getString('tier'); db.prepare('INSERT OR REPLACE INTO vip_members VALUES (?,?,?,?)').run(i.guildId,user.id,tier,null); return reply(i,'VIP added',`<@${user.id}> is now **${tier}** VIP.`);} const rows=db.prepare('SELECT user_id,tier FROM vip_members WHERE guild_id=?').all(i.guildId); return reply(i,'VIP members',rows.length?rows.map(r=>`• <@${r.user_id}> — ${r.tier}`).join('\n'):'No VIP members configured.'); }
    if (i.commandName === 'setup') return i.reply(setupPanel(i.guildId));
    if (i.commandName === 'player') { const user=i.options.getUser('user')||i.user; const row=db.prepare('SELECT username,kills,playtime FROM stats WHERE guild_id=? AND user_id=?').get(i.guildId,user.id); return reply(i,'Player record',row?`**${row.username}**\nKills: ${row.kills}\nPlaytime: ${row.playtime} minutes`:`No saved stats for <@${user.id}> yet.`); }
    if (i.commandName === 'zone') { const sub=i.options.getSubcommand(); if(sub==='create'){const id=randomUUID().slice(0,8),name=i.options.getString('name'),type=i.options.getString('type'),x=i.options.getNumber('x'),y=i.options.getNumber('y'),z=i.options.getNumber('z'),radius=i.options.getNumber('radius'); db.prepare('INSERT INTO zones VALUES (?,?,?,?,?,?,?,?)').run(id,i.guildId,name,type,x,y,z,radius); return reply(i,'Zone saved',`${name} (${type}) saved as ${id}. In-game enforcement requires the configured server adapter.`);} const rows=db.prepare('SELECT id,name,type,radius FROM zones WHERE guild_id=?').all(i.guildId); return reply(i,'Custom zones',rows.length?rows.map(r=>`• ${r.id} **${r.name}** — ${r.type}, radius ${r.radius}`).join('\n'):'No zones configured.'); }
    if (i.commandName === 'logs') { const rows=db.prepare('SELECT action,target,created_at FROM audit_logs WHERE guild_id=? ORDER BY created_at DESC LIMIT 10').all(i.guildId); return reply(i,'Recent audit logs',rows.length?rows.map(r=>`• ${r.created_at} — ${r.action}${r.target?` (${r.target})`:''}`).join('\n'):'No audit logs yet.'); }
    if (i.commandName === 'announcement') return reply(i,'Announcement ready',i.options.getString('message'));
    if (i.commandName === 'automod') { const enabled=i.options.getBoolean('enabled')?1:0,words=i.options.getString('blocked_words')||''; db.prepare('INSERT OR REPLACE INTO automod VALUES (?,?,?)').run(i.guildId,enabled,words); return reply(i,'Automod updated',enabled?`Enabled. Blocked words configured: ${words?words.split(',').length:0}.`:'Disabled.'); }
    if (i.commandName === 'maintenance') return reply(i,'Maintenance mode','Maintenance status is community-specific and will be connected to the server adapter when available.');
    if (i.commandName === 'ticket-panel') { await i.reply(ticketPanel(i.guildId)); const message=await i.fetchReply(); db.prepare('INSERT OR IGNORE INTO ticket_panels VALUES (?,?,?)').run(i.guildId,message.channelId,message.id); return; }
    if (i.commandName === 'tickets') { const total=db.prepare("SELECT COUNT(*) AS n FROM tickets WHERE guild_id=? AND status='open'").get(i.guildId).n; const eu=db.prepare("SELECT COUNT(*) AS n FROM tickets WHERE guild_id=? AND status='open' AND region='EU'").get(i.guildId).n; const na=db.prepare("SELECT COUNT(*) AS n FROM tickets WHERE guild_id=? AND status='open' AND region='NA'").get(i.guildId).n; return reply(i,'Support Status',`Open Tickets (Total): ${total}\nOpen EU Tickets: ${eu}\nOpen NA Tickets: ${na}\nResponse Speed: Fast\nEstimated Help Time: 12 mins`,[{name:'Brand',value:BRAND}]); }
    return reply(i,'Module ready','This command is scaffolded and ready for its Rust Console server adapter.');
  } catch(e) { log.error(e); if(!i.replied) await i.reply({content:'Command failed. Check the bot logs.',ephemeral:true}); }
});
client.on('error', error => log.error({err:error}, 'Discord client error'));
setInterval(() => { for (const guild of client.guilds.cache.values()) refreshTicketPanels(guild.id).catch(error => log.warn({err:error}, 'Ticket refresh failed')); }, 60000);
client.login(token).catch(error => { log.fatal({err:error}, 'Discord login failed; verify DISCORD_TOKEN'); process.exit(1); });
