import 'dotenv/config';
import { Client, GatewayIntentBits, REST, Routes, SlashCommandBuilder, PermissionFlagsBits, EmbedBuilder, ActionRowBuilder, StringSelectMenuBuilder, ButtonBuilder, ButtonStyle, ModalBuilder, TextInputBuilder, TextInputStyle, ChannelType, PermissionsBitField } from 'discord.js';
import Database from 'better-sqlite3';
import pino from 'pino';
import { randomUUID } from 'node:crypto';

const log = pino({ level: process.env.LOG_LEVEL || 'info' });
const required = ['DISCORD_TOKEN', 'DISCORD_CLIENT_ID'];
for (const key of required) if (!process.env[key]) throw new Error(`Missing ${key}. Copy .env.example to .env.`);

const db = new Database(process.env.DB_PATH || './rce-bot.sqlite');
db.pragma('journal_mode = WAL');
db.exec(`
CREATE TABLE IF NOT EXISTS clans (id TEXT PRIMARY KEY, guild_id TEXT NOT NULL, name TEXT NOT NULL, tag TEXT NOT NULL, owner_id TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS clan_members (clan_id TEXT NOT NULL, user_id TEXT NOT NULL, role TEXT NOT NULL DEFAULT 'member', PRIMARY KEY(clan_id,user_id));
CREATE TABLE IF NOT EXISTS servers (id TEXT PRIMARY KEY, guild_id TEXT NOT NULL, name TEXT NOT NULL, host TEXT NOT NULL, port INTEGER NOT NULL, rcon_secret TEXT NOT NULL, enabled INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS homes (guild_id TEXT NOT NULL, user_id TEXT NOT NULL, name TEXT NOT NULL, x REAL, y REAL, z REAL, PRIMARY KEY(guild_id,user_id,name));
CREATE TABLE IF NOT EXISTS stats (guild_id TEXT NOT NULL, user_id TEXT NOT NULL, username TEXT NOT NULL, kills INTEGER NOT NULL DEFAULT 0, playtime INTEGER NOT NULL DEFAULT 0, PRIMARY KEY(guild_id,user_id));
CREATE TABLE IF NOT EXISTS events (id TEXT PRIMARY KEY, guild_id TEXT NOT NULL, name TEXT NOT NULL, type TEXT NOT NULL, status TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS settings (guild_id TEXT PRIMARY KEY, log_channel_id TEXT, killfeed_channel_id TEXT, prefix TEXT NOT NULL DEFAULT '/');
CREATE TABLE IF NOT EXISTS scheduled_tasks (id TEXT PRIMARY KEY, guild_id TEXT NOT NULL, kind TEXT NOT NULL, payload TEXT NOT NULL, run_at TEXT NOT NULL, enabled INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS vip_members (guild_id TEXT NOT NULL, user_id TEXT NOT NULL, tier TEXT NOT NULL, expires_at TEXT, PRIMARY KEY(guild_id,user_id));
CREATE TABLE IF NOT EXISTS zones (id TEXT PRIMARY KEY, guild_id TEXT NOT NULL, name TEXT NOT NULL, type TEXT NOT NULL, x REAL NOT NULL, y REAL NOT NULL, z REAL NOT NULL, radius REAL NOT NULL);
CREATE TABLE IF NOT EXISTS audit_logs (id TEXT PRIMARY KEY, guild_id TEXT NOT NULL, actor_id TEXT NOT NULL, action TEXT NOT NULL, target TEXT, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS automod (guild_id TEXT PRIMARY KEY, enabled INTEGER NOT NULL DEFAULT 0, blocked_words TEXT NOT NULL DEFAULT '');
CREATE TABLE IF NOT EXISTS tickets (id TEXT PRIMARY KEY, guild_id TEXT NOT NULL, channel_id TEXT NOT NULL, user_id TEXT NOT NULL, region TEXT NOT NULL, category TEXT NOT NULL, question TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'open', created_at TEXT NOT NULL, closed_at TEXT);
`);

const commands = [
  new SlashCommandBuilder().setName('help').setDescription('Show all RCE bot modules'),
  new SlashCommandBuilder().setName('server').setDescription('Manage Rust Console servers').addSubcommand(s=>s.setName('list').setDescription('List configured servers')).addSubcommand(s=>s.setName('add').setDescription('Add a server').addStringOption(o=>o.setName('name').setDescription('Display name').setRequired(true)).addStringOption(o=>o.setName('host').setDescription('RCON host').setRequired(true)).addIntegerOption(o=>o.setName('port').setDescription('RCON port').setRequired(true)).addStringOption(o=>o.setName('secret').setDescription('RCON secret').setRequired(true))),
  new SlashCommandBuilder().setName('console').setDescription('Run a command on a configured RCON server').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild).addStringOption(o=>o.setName('command').setDescription('Console command').setRequired(true)).addStringOption(o=>o.setName('server').setDescription('Server name').setRequired(true)),
  new SlashCommandBuilder().setName('clan').setDescription('Clan system').addSubcommand(s=>s.setName('create').setDescription('Create a clan').addStringOption(o=>o.setName('name').setDescription('Clan name').setRequired(true)).addStringOption(o=>o.setName('tag').setDescription('Short tag').setRequired(true))).addSubcommand(s=>s.setName('info').setDescription('View your clan')).addSubcommand(s=>s.setName('invite').setDescription('Invite a member').addUserOption(o=>o.setName('user').setDescription('Member').setRequired(true))),
  new SlashCommandBuilder().setName('event').setDescription('Events: Nuketown, KOTH, Maze, Snowroams and more').addSubcommand(s=>s.setName('start').setDescription('Start an event').addStringOption(o=>o.setName('type').setDescription('Event type').setRequired(true).addChoices(...['Nuketown','KOTH','Maze','Snowroams','Custom'].map(x=>({name:x,value:x.toLowerCase()}))))).addSubcommand(s=>s.setName('list').setDescription('List active events')).addSubcommand(s=>s.setName('end').setDescription('End an event').addStringOption(o=>o.setName('id').setDescription('Event ID').setRequired(true))),
  new SlashCommandBuilder().setName('leaderboard').setDescription('View leaderboards').addStringOption(o=>o.setName('type').setDescription('Leaderboard').setRequired(true).addChoices({name:'Kills',value:'kills'},{name:'Playtime',value:'playtime'},{name:'Events',value:'events'})),
  new SlashCommandBuilder().setName('home').setDescription('TP home system').addSubcommand(s=>s.setName('set').setDescription('Save a home').addStringOption(o=>o.setName('name').setDescription('Home name').setRequired(true)).addNumberOption(o=>o.setName('x').setDescription('X').setRequired(true)).addNumberOption(o=>o.setName('y').setDescription('Y').setRequired(true)).addNumberOption(o=>o.setName('z').setDescription('Z').setRequired(true))).addSubcommand(s=>s.setName('list').setDescription('List homes')).addSubcommand(s=>s.setName('remove').setDescription('Remove a home').addStringOption(o=>o.setName('name').setDescription('Home name').setRequired(true))),
  new SlashCommandBuilder().setName('kit').setDescription('Automatic kits').addSubcommand(s=>s.setName('give').setDescription('Give a kit').addStringOption(o=>o.setName('name').setDescription('Kit name').setRequired(true)).addUserOption(o=>o.setName('user').setDescription('Target'))),
  new SlashCommandBuilder().setName('vip').setDescription('VIP management').addSubcommand(s=>s.setName('add').setDescription('Add VIP').addUserOption(o=>o.setName('user').setDescription('User').setRequired(true)).addStringOption(o=>o.setName('tier').setDescription('Tier').setRequired(true))).addSubcommand(s=>s.setName('list').setDescription('List VIP members')),
  new SlashCommandBuilder().setName('config').setDescription('Configure logs, kill feed and automation').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild).addStringOption(o=>o.setName('log_channel').setDescription('Log channel ID')).addStringOption(o=>o.setName('killfeed_channel').setDescription('Kill feed channel ID')),
  new SlashCommandBuilder().setName('schedule').setDescription('Schedule a message or server command').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild).addStringOption(o=>o.setName('kind').setDescription('message or command').setRequired(true).addChoices({name:'Message',value:'message'},{name:'Command',value:'command'})).addStringOption(o=>o.setName('payload').setDescription('Message or console command').setRequired(true)).addStringOption(o=>o.setName('run_at').setDescription('Future ISO time').setRequired(true)),
  new SlashCommandBuilder().setName('setup').setDescription('Show the community setup checklist'),
  new SlashCommandBuilder().setName('player').setDescription('Player tools').addSubcommand(s=>s.setName('info').setDescription('View a player record').addUserOption(o=>o.setName('user').setDescription('Discord user'))).addSubcommand(s=>s.setName('stats').setDescription('View saved stats').addUserOption(o=>o.setName('user').setDescription('Discord user'))),
  new SlashCommandBuilder().setName('zone').setDescription('Custom zones').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild).addSubcommand(s=>s.setName('create').setDescription('Create a zone').addStringOption(o=>o.setName('name').setDescription('Zone name').setRequired(true)).addStringOption(o=>o.setName('type').setDescription('Zone type').setRequired(true)).addNumberOption(o=>o.setName('x').setDescription('X').setRequired(true)).addNumberOption(o=>o.setName('y').setDescription('Y').setRequired(true)).addNumberOption(o=>o.setName('z').setDescription('Z').setRequired(true)).addNumberOption(o=>o.setName('radius').setDescription('Radius').setRequired(true))).addSubcommand(s=>s.setName('list').setDescription('List zones')).addSubcommand(s=>s.setName('delete').setDescription('Delete a zone').addStringOption(o=>o.setName('id').setDescription('Zone ID').setRequired(true))),
  new SlashCommandBuilder().setName('logs').setDescription('View recent bot audit logs').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild),
  new SlashCommandBuilder().setName('announcement').setDescription('Create a community announcement').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild).addStringOption(o=>o.setName('message').setDescription('Announcement text').setRequired(true)),
  new SlashCommandBuilder().setName('automod').setDescription('Configure basic automod').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild).addBooleanOption(o=>o.setName('enabled').setDescription('Enable automod').setRequired(true)).addStringOption(o=>o.setName('blocked_words').setDescription('Comma-separated words')),
  new SlashCommandBuilder().setName('maintenance').setDescription('Show maintenance mode status').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild),
  new SlashCommandBuilder().setName('ticket-panel').setDescription('Post the Rustworks RCE support ticket panel').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild),
  new SlashCommandBuilder().setName('tickets').setDescription('Show support ticket status').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild)
].map(c=>c.toJSON());

const client = new Client({ intents: [GatewayIntentBits.Guilds, GatewayIntentBits.GuildMembers, GatewayIntentBits.GuildMessages] });
const BRAND = 'rustworks • RCE';
const ticketPanel = () => {
  const menu = new StringSelectMenuBuilder().setCustomId('ticket_category').setPlaceholder('Select a support option').addOptions(
    {label:'Rust Console Support',value:'rust_support',description:'Server, gameplay, RCON, and player help',emoji:'🛠️'},
    {label:'Bot Support',value:'bot_support',description:'Discord bot setup and command help',emoji:'🤖'},
    {label:'Report a Problem',value:'report',description:'Report a bug or community issue',emoji:'🚨'}
  );
  return {embeds:[new EmbedBuilder().setColor(0x8b5cf6).setTitle('Support Tickets').setDescription('Select a support option, then choose EU or NA before filling your questions.').addFields({name:'Support Status',value:'Open Tickets (Total): 0\nOpen EU Tickets: 0\nOpen NA Tickets: 0\nResponse Speed: Fast\nEstimated Help Time: 12 mins'}).setFooter({text:BRAND})],components:[new ActionRowBuilder().addComponents(menu)]};
};
const reply = (i, title, description, fields=[]) => i.reply({ embeds: [new EmbedBuilder().setColor(0x8b5cf6).setTitle(title).setDescription(description).addFields(fields)] });

client.once('ready', async () => { const rest = new REST({version:'10'}).setToken(process.env.DISCORD_TOKEN); await rest.put(Routes.applicationCommands(process.env.DISCORD_CLIENT_ID), {body:commands}); await client.user.setPresence({activities:[{name:'Rust Console communities',type:0}],status:'online'}); log.info({user:client.user.tag,brand:BRAND}, 'Rustworks RCE bot online'); });
client.on('interactionCreate', async i => {
  try {
    if (i.isStringSelectMenu() && i.customId === 'ticket_category') {
      const category=i.values[0];
      const regionMenu=new StringSelectMenuBuilder().setCustomId(`ticket_region:${category}`).setPlaceholder('Choose your region').addOptions({label:'EU',value:'EU',description:'European support team'},{label:'NA',value:'NA',description:'North American support team'});
      return i.update({components:[new ActionRowBuilder().addComponents(regionMenu)]});
    }
    if (i.isStringSelectMenu() && i.customId.startsWith('ticket_region:')) {
      const category=i.customId.split(':')[1],region=i.values[0];
      const modal=new ModalBuilder().setCustomId(`ticket_modal:${category}:${region}`).setTitle(`${region} support ticket`);
      const question=new TextInputBuilder().setCustomId('question').setLabel('How can we help?').setStyle(TextInputStyle.Paragraph).setPlaceholder('Tell us what happened and include your server/player details.').setRequired(true).setMaxLength(1800);
      return i.showModal(modal.addComponents(new ActionRowBuilder().addComponents(question)));
    }
    if (i.isModalSubmit() && i.customId.startsWith('ticket_modal:')) {
      const [,category,region]=i.customId.split(':'), question=i.fields.getTextInputValue('question'), guild=i.guild;
      const safeName=`${region.toLowerCase()}-${i.user.username}`.toLowerCase().replace(/[^a-z0-9-]/g,'').slice(0,70);
      const channel=await guild.channels.create({name:`ticket-${safeName}`,type:ChannelType.GuildText,topic:`${BRAND} | ${region} | ${category} | ${i.user.id}`,permissionOverwrites:[{id:guild.roles.everyone.id,deny:[PermissionsBitField.Flags.ViewChannel]},{id:i.user.id,allow:[PermissionsBitField.Flags.ViewChannel,PermissionsBitField.Flags.SendMessages,PermissionsBitField.Flags.ReadMessageHistory]},{id:guild.members.me.id,allow:[PermissionsBitField.Flags.ViewChannel,PermissionsBitField.Flags.SendMessages,PermissionsBitField.Flags.ManageChannels]}]});
      const id=randomUUID(); db.prepare('INSERT INTO tickets VALUES (?,?,?,?,?,?,?,?,?,?)').run(id,guild.id,channel.id,i.user.id,region,category,question,'open',new Date().toISOString(),null);
      const close=new ButtonBuilder().setCustomId(`ticket_close:${id}`).setLabel('Close ticket').setStyle(ButtonStyle.Danger);
      await channel.send({content:`<@${i.user.id}>`,embeds:[new EmbedBuilder().setColor(0x8b5cf6).setTitle('Support Ticket').setDescription(question).addFields({name:'Region',value:region,inline:true},{name:'Category',value:category,inline:true}).setFooter({text:BRAND})],components:[new ActionRowBuilder().addComponents(close)]});
      return i.reply({content:`Your ${region} support ticket is open: ${channel}`,ephemeral:true});
    }
    if (i.isButton() && i.customId.startsWith('ticket_close:')) { const id=i.customId.split(':')[1]; db.prepare('UPDATE tickets SET status=\'closed\',closed_at=? WHERE id=?').run(new Date().toISOString(),id); await i.reply({content:'Ticket closed. This channel will be removed in 5 seconds.',ephemeral:true}); setTimeout(()=>i.channel?.delete().catch(()=>{}),5000); return; }
    if (!i.isChatInputCommand()) return;
    if (i.commandName === 'help') return reply(i, 'RCE Bot Command Centre', 'Free, original Rust Console Edition community tooling.', [{name:'Core',value:'/server · /console · /config'},{name:'Community',value:'/clan · /leaderboard · /vip'},{name:'Gameplay',value:'/event · /kit · /home'}]);
    if (i.commandName === 'server') { if(i.options.getSubcommand()==='add'){const n=i.options.getString('name'),h=i.options.getString('host'),p=i.options.getInteger('port'),s=i.options.getString('secret'); db.prepare('INSERT INTO servers VALUES (?,?,?,?,?,1)').run(randomUUID(),i.guildId,n,h,p,s); return reply(i,'Server added',`**${n}** is saved. RCON execution is kept behind the adapter boundary.`);} const rows=db.prepare('SELECT name,host,port FROM servers WHERE guild_id=?').all(i.guildId); return reply(i,'Configured servers',rows.length?rows.map(r=>`• **${r.name}** — ${r.host}:${r.port}`).join('\n'):'No servers configured yet.'); }
    if (i.commandName === 'clan') { const sub=i.options.getSubcommand(); if(sub==='create'){const name=i.options.getString('name'),tag=i.options.getString('tag'); const id=randomUUID(); db.prepare('INSERT INTO clans VALUES (?,?,?,?,?,?)').run(id,i.guildId,name,tag,i.user.id,new Date().toISOString()); db.prepare('INSERT INTO clan_members VALUES (?,?,?)').run(id,i.user.id,'owner'); return reply(i,'Clan created',`**[${tag}] ${name}** is ready.`);} const c=db.prepare('SELECT c.* FROM clans c JOIN clan_members m ON m.clan_id=c.id WHERE c.guild_id=? AND m.user_id=?').get(i.guildId,i.user.id); return reply(i,'Clan info',c?`**[${c.tag}] ${c.name}**\nOwner: <@${c.owner_id}>`:'You are not in a clan.'); }
    if (i.commandName === 'event') { const sub=i.options.getSubcommand(); if(sub==='start'){const type=i.options.getString('type'),id=randomUUID().slice(0,8); db.prepare('INSERT INTO events VALUES (?,?,?,?,?,?)').run(id,i.guildId,type,type,'active',new Date().toISOString()); return reply(i,'Event started',`**${type}** is live. Event ID: ${id}`);} const rows=db.prepare("SELECT id,name,type,status FROM events WHERE guild_id=? AND status='active'").all(i.guildId); return reply(i,'Active events',rows.length?rows.map(r=>`• ${r.id} **${r.name}** — ${r.type}`).join('\n'):'No active events.'); }
    if (i.commandName === 'leaderboard') { const type=i.options.getString('type'); if(type==='events') return reply(i,'Event leaderboard','Event placements will appear here as event results are recorded.'); const rows=db.prepare(`SELECT username,${type} AS score FROM stats WHERE guild_id=? ORDER BY score DESC LIMIT 10`).all(i.guildId); return reply(i,`${type[0].toUpperCase()+type.slice(1)} leaderboard`,rows.length?rows.map((r,n)=>`**${n+1}.** ${r.username} — ${r.score}`).join('\n'):'No player stats recorded yet.'); }
    if (i.commandName === 'home') { const sub=i.options.getSubcommand(); if(sub==='set'){db.prepare('INSERT OR REPLACE INTO homes VALUES (?,?,?,?,?)').run(i.guildId,i.user.id,i.options.getString('name'),i.options.getNumber('x'),i.options.getNumber('y'),i.options.getNumber('z')); return reply(i,'Home saved','Coordinates saved for the RCON teleport adapter.');} const rows=db.prepare('SELECT name,x,y,z FROM homes WHERE guild_id=? AND user_id=?').all(i.guildId,i.user.id); return reply(i,'Your homes',rows.length?rows.map(r=>`• **${r.name}** — ${r.x}, ${r.y}, ${r.z}`).join('\n'):'No homes saved.'); }
    if (i.commandName === 'schedule') { const kind=i.options.getString('kind'),payload=i.options.getString('payload'),runAt=i.options.getString('run_at'); if(Number.isNaN(Date.parse(runAt)) || Date.parse(runAt)<=Date.now()) return reply(i,'Invalid schedule','Use a future ISO timestamp.'); db.prepare('INSERT INTO scheduled_tasks VALUES (?,?,?,?,?,1)').run(randomUUID(),i.guildId,kind,payload,new Date(runAt).toISOString()); return reply(i,'Scheduled',`${kind} task saved for ${new Date(runAt).toISOString()}.`); }
    if (i.commandName === 'vip') { const sub=i.options.getSubcommand(); if(sub==='add'){const user=i.options.getUser('user'),tier=i.options.getString('tier'); db.prepare('INSERT OR REPLACE INTO vip_members VALUES (?,?,?,?)').run(i.guildId,user.id,tier,null); return reply(i,'VIP added',`<@${user.id}> is now **${tier}** VIP.`);} const rows=db.prepare('SELECT user_id,tier FROM vip_members WHERE guild_id=?').all(i.guildId); return reply(i,'VIP members',rows.length?rows.map(r=>`• <@${r.user_id}> — ${r.tier}`).join('\n'):'No VIP members configured.'); }
    if (i.commandName === 'setup') return reply(i,'Community setup checklist','1. Add a server with `/server add`.\n2. Configure `/config`.\n3. Choose log and kill-feed channels.\n4. Confirm the Rust provider RCON/API method.\n5. Test safe status/player commands.');
    if (i.commandName === 'player') { const user=i.options.getUser('user')||i.user; const row=db.prepare('SELECT username,kills,playtime FROM stats WHERE guild_id=? AND user_id=?').get(i.guildId,user.id); return reply(i,'Player record',row?`**${row.username}**\nKills: ${row.kills}\nPlaytime: ${row.playtime} minutes`:`No saved stats for <@${user.id}> yet.`); }
    if (i.commandName === 'zone') { const sub=i.options.getSubcommand(); if(sub==='create'){const id=randomUUID().slice(0,8),name=i.options.getString('name'),type=i.options.getString('type'),x=i.options.getNumber('x'),y=i.options.getNumber('y'),z=i.options.getNumber('z'),radius=i.options.getNumber('radius'); db.prepare('INSERT INTO zones VALUES (?,?,?,?,?,?,?,?)').run(id,i.guildId,name,type,x,y,z,radius); return reply(i,'Zone saved',`${name} (${type}) saved as ${id}. In-game enforcement requires the configured server adapter.`);} const rows=db.prepare('SELECT id,name,type,radius FROM zones WHERE guild_id=?').all(i.guildId); return reply(i,'Custom zones',rows.length?rows.map(r=>`• ${r.id} **${r.name}** — ${r.type}, radius ${r.radius}`).join('\n'):'No zones configured.'); }
    if (i.commandName === 'logs') { const rows=db.prepare('SELECT action,target,created_at FROM audit_logs WHERE guild_id=? ORDER BY created_at DESC LIMIT 10').all(i.guildId); return reply(i,'Recent audit logs',rows.length?rows.map(r=>`• ${r.created_at} — ${r.action}${r.target?` (${r.target})`:''}`).join('\n'):'No audit logs yet.'); }
    if (i.commandName === 'announcement') return reply(i,'Announcement ready',i.options.getString('message'));
    if (i.commandName === 'automod') { const enabled=i.options.getBoolean('enabled')?1:0,words=i.options.getString('blocked_words')||''; db.prepare('INSERT OR REPLACE INTO automod VALUES (?,?,?)').run(i.guildId,enabled,words); return reply(i,'Automod updated',enabled?`Enabled. Blocked words configured: ${words?words.split(',').length:0}.`:'Disabled.'); }
    if (i.commandName === 'maintenance') return reply(i,'Maintenance mode','Maintenance status is community-specific and will be connected to the server adapter when available.');
    if (i.commandName === 'ticket-panel') return i.reply(ticketPanel());
    if (i.commandName === 'tickets') { const total=db.prepare("SELECT COUNT(*) AS n FROM tickets WHERE guild_id=? AND status='open'").get(i.guildId).n; const eu=db.prepare("SELECT COUNT(*) AS n FROM tickets WHERE guild_id=? AND status='open' AND region='EU'").get(i.guildId).n; const na=db.prepare("SELECT COUNT(*) AS n FROM tickets WHERE guild_id=? AND status='open' AND region='NA'").get(i.guildId).n; return reply(i,'Support Status',`Open Tickets (Total): ${total}\nOpen EU Tickets: ${eu}\nOpen NA Tickets: ${na}\nResponse Speed: Fast\nEstimated Help Time: 12 mins`,[{name:'Brand',value:BRAND}]); }
    return reply(i,'Module ready','This command is scaffolded and ready for its Rust Console server adapter.');
  } catch(e) { log.error(e); if(!i.replied) await i.reply({content:'Command failed. Check the bot logs.',ephemeral:true}); }
});
client.login(process.env.DISCORD_TOKEN);
